// ATTENTION!
// This file is generated via the script generateItemsFile.js and should not be edited manually.
// All item objects are sorted by name.

export type Item = { id: string; name: string; civilian?: boolean };

export const HEAD_ARMORS: Record<string, Item> = {
  vlandia_crown: { id: "vlandia_crown", name: "Austere Crown", civilian: true  },
  aserai_civil_f_cape: { id: "aserai_civil_f_cape", name: "Bandit Leather Hood", civilian: true  },
  sturgian_battle_crown: { id: "sturgian_battle_crown", name: "Battle Crown" },
  bearhead: { id: "bearhead", name: "Bear Head" },
  battania_earmuff_helmet_b_brnz: { id: "battania_earmuff_helmet_b_brnz", name: "Bronze Cap with Cheek Guards" },
  leatherlame_nasalhelm_over_imperial_mail: { id: "leatherlame_nasalhelm_over_imperial_mail", name: "Bronze Nasalhelm over Mail" },
  battania_fur_helmet: { id: "battania_fur_helmet", name: "Cap with Fur Coif" },
  eastern_cap: { id: "eastern_cap", name: "Cap with Neck Flap", civilian: true  },
  cervelliere_over_arming_coif: { id: "cervelliere_over_arming_coif", name: "Cervelliere over Arming Coif" },
  cervelliere_over_cloth_headwrap: { id: "cervelliere_over_cloth_headwrap", name: "Cervelliere over Cloth Headwrap" },
  cervelliere_over_laced_coif: { id: "cervelliere_over_laced_coif", name: "Cervelliere over Laced Coif" },
  cervelliere_over_padded_cap: { id: "cervelliere_over_padded_cap", name: "Cervelliere over Padded Cap" },
  sturgian_helmet_b_close: { id: "sturgian_helmet_b_close", name: "Closed Decorated Goggled Helmet" },
  closed_head_scarf: { id: "closed_head_scarf", name: "Closed Head Scarf" },
  goggled_helmet_over_full_mail: { id: "goggled_helmet_over_full_mail", name: "Closed Huscarl Helmet" },
  vlandian_faceguard_helmet_a: { id: "vlandian_faceguard_helmet_a", name: "Closed Knight Helmet" },
  nordic_helmet: { id: "nordic_helmet", name: "Closed Mail Goggled Helmet" },
  closed_desert_helmet_with_mail: { id: "closed_desert_helmet_with_mail", name: "Closed Steel Cap" },
  sturgian_helmet_closed: { id: "sturgian_helmet_closed", name: "Closed Warlord Helmet" },
  imperial_cloth_coif: { id: "imperial_cloth_coif", name: "Cloth Coif", civilian: true  },
  cloth_headwrap: { id: "cloth_headwrap", name: "Cloth Headwrap", civilian: true  },
  battania_civil_hood: { id: "battania_civil_hood", name: "Cloth Hood" },
  head_scarf: { id: "head_scarf", name: "Colored Hijab", civilian: true  },
  aserai_civil_e_hscarf: { id: "aserai_civil_e_hscarf", name: "Colored Kefiyyeh", civilian: true  },
  aserai_civil_d_hscarf: { id: "aserai_civil_d_hscarf", name: "Colored Turban", civilian: true  },
  western_crowned_helmet: { id: "western_crowned_helmet", name: "Crowned Helmet" },
  western_crowned_plated_helmet: { id: "western_crowned_plated_helmet", name: "Crowned Plate Helmet" },
  battania_earmuff_helmet_c_cpr: { id: "battania_earmuff_helmet_c_cpr", name: "Decorated Bronze Helmet with Cheek Guards" },
  decorated_nomad_cap: { id: "decorated_nomad_cap", name: "Decorated Nomad Cap", civilian: true  },
  desert_headdress: { id: "desert_headdress", name: "Desert Headdress", civilian: true  },
  aserai_female_civil_hscarf: { id: "aserai_female_civil_hscarf", name: "Desert Headscarf", civilian: true  },
  emirs_helmet: { id: "emirs_helmet", name: "Emir Helmet" },
  ironlame_feathered_spangenhelm: { id: "ironlame_feathered_spangenhelm", name: "Feathered Spangenhelm" },
  feathered_spangenhelm_over_imperial_coif: { id: "feathered_spangenhelm_over_imperial_coif", name: "Feathered Spangenhelm over Coif" },
  ironlame_feathered_spangenhelm_over_leather: { id: "ironlame_feathered_spangenhelm_over_leather", name: "Feathered Spangenhelm over Leather" },
  leatherlame_feathered_spangenhelm_over_mail: { id: "leatherlame_feathered_spangenhelm_over_mail", name: "Feathered Spangenhelm over Mail" },
  female_head_wrap: { id: "female_head_wrap", name: "Female Head Wrap", civilian: true  },
  head_wrapped: { id: "head_wrapped", name: "Female Rural Head Wrap", civilian: true  },
  head_piece: { id: "head_piece", name: "Female Rural Scarf", civilian: true  },
  battania_earmuff_helmet_a_brnz: { id: "battania_earmuff_helmet_a_brnz", name: "Fringed Bronze Cap with Cheek Guards" },
  battania_earmuff_helmet_c_brnz: { id: "battania_earmuff_helmet_c_brnz", name: "Fringed Decorated Bronze Cap with Cheek Guards" },
  battania_earmuff_helmet_c: { id: "battania_earmuff_helmet_c", name: "Fringed Decorated Steel Cap with Cheek Guards" },
  battania_earmuff_helmet_a: { id: "battania_earmuff_helmet_a", name: "Fringed Steel Cap with Cheek Guards" },
  full_helm_over_arming_coif: { id: "full_helm_over_arming_coif", name: "Full Helm over Arming Coif" },
  full_helm_over_cloth_headwrap: { id: "full_helm_over_cloth_headwrap", name: "Full Helm over Cloth Headwrap" },
  full_helm_over_laced_coif: { id: "full_helm_over_laced_coif", name: "Full Helm over Laced Coif" },
  full_helm_over_mail_coif: { id: "full_helm_over_mail_coif", name: "Full Helm over Mail Coif" },
  full_helm_over_padded_cap: { id: "full_helm_over_padded_cap", name: "Full Helm over Padded Cap" },
  full_helm_over_padded_cloth: { id: "full_helm_over_padded_cloth", name: "Full Helm over Padded Cloth" },
  northern_fur_cap: { id: "northern_fur_cap", name: "Fur Cap", civilian: true  },
  nordic_leather_cap: { id: "nordic_leather_cap", name: "Fur Cap with Ear Flaps", civilian: true  },
  nordic_fur_cap: { id: "nordic_fur_cap", name: "Fur Rimmed Cap", civilian: true  },
  khuzait_noble_helmet_with_fur: { id: "khuzait_noble_helmet_with_fur", name: "Furred Noble Lancer Helmet" },
  khuzait_noble_helmet_with_neckguard: { id: "khuzait_noble_helmet_with_neckguard", name: "Furred Noble Lancer Helmet with Neckguard" },
  imperial_goggled_helmet: { id: "imperial_goggled_helmet", name: "Goggled Cataphract Helmet" },
  goggled_helmet_over_leather: { id: "goggled_helmet_over_leather", name: "Goggled Helmet over Leather" },
  goggled_helmet_over_mail: { id: "goggled_helmet_over_mail", name: "Goggled Helmet over Mail" },
  empire_crown_north: { id: "empire_crown_north", name: "Golden Laurel Crown", civilian: true  },
  womens_headwrap_b: { id: "womens_headwrap_b", name: "Head Scarf", civilian: true  },
  aserai_female_civil_hscarf_b: { id: "aserai_female_civil_hscarf_b", name: "Headscarf with Fez", civilian: true  },
  sturgia_heavy_cavalary_helmet: { id: "sturgia_heavy_cavalary_helmet", name: "Heavy Cavalry Helmet" },
  eastern_vendel_helmet: { id: "eastern_vendel_helmet", name: "Heavy Lancer Helmet" },
  heavy_nasalhelm_over_laced_cloth: { id: "heavy_nasalhelm_over_laced_cloth", name: "Heavy Nasalhelm over Laced Cloth" },
  heavy_nasalhelm_over_imperial_leather: { id: "heavy_nasalhelm_over_imperial_leather", name: "Heavy Nasalhelm over Leather" },
  heavy_nasalhelm_over_imperial_mail: { id: "heavy_nasalhelm_over_imperial_mail", name: "Heavy Nasalhelm over Mail" },
  heavy_nasalhelm_over_imperial_padding: { id: "heavy_nasalhelm_over_imperial_padding", name: "Heavy Nasalhelm over Padding" },
  helmet_with_faceguard: { id: "helmet_with_faceguard", name: "Helmet with Faceguard" },
  loose_wrapped_desert_helmet: { id: "loose_wrapped_desert_helmet", name: "Helmet with Open Turban" },
  trailed_desert_helmet: { id: "trailed_desert_helmet", name: "Helmet with Turban and Coif" },
  vlandia_bandit_cape_b: { id: "vlandia_bandit_cape_b", name: "Hide Cap" },
  battania_crown: { id: "battania_crown", name: "Highland Ceremonial Crown" },
  battanian_crowned_helmet: { id: "battanian_crowned_helmet", name: "Highland Crowned Helmet" },
  headscarf_d: { id: "headscarf_d", name: "Hijab", civilian: true  },
  empire_crown_v2: { id: "empire_crown_v2", name: "Imperial Jeweled Band", civilian: true  },
  empire_crown_west: { id: "empire_crown_west", name: "Imperial Jeweled Band", civilian: true  },
  empire_jewelled_helmet: { id: "empire_jewelled_helmet", name: "Imperial Jewelled Helmet" },
  empire_battle_crown_west: { id: "empire_battle_crown_west", name: "Imperial Plumed Helmet" },
  steppe_helmet: { id: "steppe_helmet", name: "Infantry Steel Helmet" },
  ironlame_nasalhelm_over_imperial_cloth: { id: "ironlame_nasalhelm_over_imperial_cloth", name: "Iron Legionary Helm over Cloth" },
  ironlame_nasalhelm_over_imperial_coif: { id: "ironlame_nasalhelm_over_imperial_coif", name: "Iron Nasalhelm over Coif" },
  leatherlame_nasalhelm_over_imperial_leather: { id: "leatherlame_nasalhelm_over_imperial_leather", name: "Iron Nasalhelm over Leather" },
  ironlame_nasalhelm_over_imperial_mail: { id: "ironlame_nasalhelm_over_imperial_mail", name: "Iron Nasalhelm over Mail" },
  ironlame_nasalhelm_over_imperial_padding: { id: "ironlame_nasalhelm_over_imperial_padding", name: "Iron Nasalhelm over Padding" },
  ironlame_roundkettle_over_imperial_leather: { id: "ironlame_roundkettle_over_imperial_leather", name: "Iron Roundkettle over Leather" },
  ironlame_roundkettle_over_imperial_mail: { id: "ironlame_roundkettle_over_imperial_mail", name: "Iron Roundkettle over Mail" },
  ironlame_spiked_kettle_over_mail: { id: "ironlame_spiked_kettle_over_mail", name: "Iron Spiked Kettle over Mail" },
  empire_crown: { id: "empire_crown", name: "Jeweled Crown" },
  sturgian_crown: { id: "sturgian_crown", name: "Jeweled Fur Rimmed Helmet", civilian: true  },
  empire_battle_crown_north: { id: "empire_battle_crown_north", name: "Jeweled Plumed Battle Crown" },
  aserai_civil_hscarf_a: { id: "aserai_civil_hscarf_a", name: "Kefiyyeh with Brown Band", civilian: true  },
  aserai_civil_c_head: { id: "aserai_civil_c_head", name: "Kefiyyeh with Silken Band", civilian: true  },
  kettle_hat_over_mail_coif: { id: "kettle_hat_over_mail_coif", name: "Kettle Hat over Mail Coif" },
  kettle_hat_over_padded_cloth: { id: "kettle_hat_over_padded_cloth", name: "Kettle Hat over Padded Cloth" },
  kettle_hat_over_padded_coif: { id: "kettle_hat_over_padded_coif", name: "Kettle Hat over Padded Coif" },
  kettle_helmet_over_arming_coif: { id: "kettle_helmet_over_arming_coif", name: "Kettle Helmet over Arming Coif" },
  kettle_helmet_over_laced_coif: { id: "kettle_helmet_over_laced_coif", name: "Kettle Helmet over Laced Coif" },
  kettle_helmet_over_mail: { id: "kettle_helmet_over_mail", name: "Kettle Helmet over Mail" },
  kettle_helmet_over_padded_cap: { id: "kettle_helmet_over_padded_cap", name: "Kettle Helmet over Padded Cap" },
  kettle_helmet_over_padded_cloth: { id: "kettle_helmet_over_padded_cloth", name: "Kettle Helmet over Padded Cloth" },
  kettle_helmet_over_padded_coif: { id: "kettle_helmet_over_padded_coif", name: "Kettle Helmet over Padded Coif" },
  kettle_helmet_with_leather: { id: "kettle_helmet_with_leather", name: "Kettle Helmet with Leather" },
  kettle_helmet_with_mail: { id: "kettle_helmet_with_mail", name: "Kettle Helmet with Mail" },
  guards_kettle_over_laced_coif: { id: "guards_kettle_over_laced_coif", name: "Kettle over Laced Coif" },
  guards_kettle_over_mail_coif: { id: "guards_kettle_over_mail_coif", name: "Kettle over Mail Coif" },
  guards_kettle_over_padded_coif: { id: "guards_kettle_over_padded_coif", name: "Kettle over Padded Coif" },
  khuzait_battle_crown: { id: "khuzait_battle_crown", name: "Khuzait Battle Crown" },
  vlandian_faceguard_helmet_b: { id: "vlandian_faceguard_helmet_b", name: "Knight Helmet with Bronze Faceguard" },
  laced_cloth_coif: { id: "laced_cloth_coif", name: "Laced Cloth Coif", civilian: true  },
  laced_coif: { id: "laced_coif", name: "Laced Coif", civilian: true  },
  leather_cap: { id: "leather_cap", name: "Leather Cap", civilian: true  },
  arming_coif: { id: "arming_coif", name: "Leather Coif", civilian: true  },
  imperial_leather_coif: { id: "imperial_leather_coif", name: "Leather Coif", civilian: true  },
  leather_studdedhelm: { id: "leather_studdedhelm", name: "Leather Studded Helm" },
  leather_studdedhelm_over_headcloth: { id: "leather_studdedhelm_over_headcloth", name: "Leather Studdedhelm over Headcloth" },
  leather_studdedhelm_over_roughscale: { id: "leather_studdedhelm_over_roughscale", name: "Leather Studdedhelm over Roughscale" },
  leather_studdedhelm_over_thinhide: { id: "leather_studdedhelm_over_thinhide", name: "Leather Studdedhelm over Thinhide" },
  imperial_nasal_helm: { id: "imperial_nasal_helm", name: "Legionary Helm" },
  roundkettle_over_imperial_leather: { id: "roundkettle_over_imperial_leather", name: "Light Roundkettle over Leather" },
  imperial_padded_coif: { id: "imperial_padded_coif", name: "Lightweight Padded Coif", civilian: true  },
  headscarf: { id: "headscarf", name: "Loose Head Scarf", civilian: true  },
  southern_lord_helmet: { id: "southern_lord_helmet", name: "Lordly Steel Cap" },
  empire_helmet_with_metal_strips: { id: "empire_helmet_with_metal_strips", name: "Lords Helmet with Metal Strips" },
  headscarf_c: { id: "headscarf_c", name: "Luxurious Head Scarf", civilian: true  },
  imperial_mail_coif: { id: "imperial_mail_coif", name: "Mail Coif" },
  mail_coif: { id: "mail_coif", name: "Mail Coif with Helmet Padding" },
  sturgian_helmet_open: { id: "sturgian_helmet_open", name: "Mailed Nasal Helmet" },
  desert_helmet_with_mail: { id: "desert_helmet_with_mail", name: "Mameluke Helmet with Mail" },
  merchants_hat: { id: "merchants_hat", name: "Merchant Hat", civilian: true  },
  nasal_cervelliere_over_laced_coif: { id: "nasal_cervelliere_over_laced_coif", name: "Nasal Cervelliere over Laced Coif" },
  nasal_cervelliere_over_mail_coif: { id: "nasal_cervelliere_over_mail_coif", name: "Nasal Cervelliere over Mail Coif" },
  nasal_cervelliere_over_padded_cap: { id: "nasal_cervelliere_over_padded_cap", name: "Nasal Cervelliere over Padded Cap" },
  nasal_cervelliere_over_padded_coif: { id: "nasal_cervelliere_over_padded_coif", name: "Nasal Cervelliere over Padded Coif" },
  nasal_helmet_over_cloth_headwrap: { id: "nasal_helmet_over_cloth_headwrap", name: "Nasal Helmet over Cloth Headwrap" },
  nasal_helmet_over_laced_coif: { id: "nasal_helmet_over_laced_coif", name: "Nasal Helmet over Laced Coif" },
  nasal_helmet_over_mail: { id: "nasal_helmet_over_mail", name: "Nasal Helmet over Mail" },
  nasal_helmet_over_mail_coif: { id: "nasal_helmet_over_mail_coif", name: "Nasal Helmet over Mail Coif" },
  nasal_helmet_over_padded_cloth: { id: "nasal_helmet_over_padded_cloth", name: "Nasal Helmet over Padded Cloth" },
  nasal_helmet_over_padded_coif: { id: "nasal_helmet_over_padded_coif", name: "Nasal Helmet over Padded Coif" },
  nasal_helmet_with_leather: { id: "nasal_helmet_with_leather", name: "Nasal Helmet with Leather" },
  nasal_helmet_with_mail: { id: "nasal_helmet_with_mail", name: "Nasal Helmet with Mail" },
  nasalhelm_over_leather: { id: "nasalhelm_over_leather", name: "Nasalhelm over Leather" },
  nasalhelm_over_mail: { id: "nasalhelm_over_mail", name: "Nasalhelm over Mail" },
  khuzait_noble_helmet_with_feathers: { id: "khuzait_noble_helmet_with_feathers", name: "Noble Lancer Helmet" },
  nomad_cap: { id: "nomad_cap", name: "Nomad Cap", civilian: true  },
  fur_hat: { id: "fur_hat", name: "Nomad Fur Cap", civilian: true  },
  nomad_helmet: { id: "nomad_helmet", name: "Nomad Helmet" },
  nomad_padded_hood: { id: "nomad_padded_hood", name: "Nomad Padded Hood", civilian: true  },
  open_head_scarf: { id: "open_head_scarf", name: "Open Head Scarf", civilian: true  },
  imperial_open_mail_coif: { id: "imperial_open_mail_coif", name: "Open Mail Coif" },
  open_mail_coif: { id: "open_mail_coif", name: "Open Mail Coif" },
  open_padded_coif: { id: "open_padded_coif", name: "Open Padded Coif", civilian: true  },
  aserai_battle_crown: { id: "aserai_battle_crown", name: "Ornate Desert Battle Crown" },
  khuzait_crown: { id: "khuzait_crown", name: "Ornate Steel Cap" },
  padded_cap: { id: "padded_cap", name: "Padded Cap", civilian: true  },
  arming_cap: { id: "arming_cap", name: "Padded Coif" },
  padded_coif: { id: "padded_coif", name: "Padded Half Coif" },
  padded_leather_cape: { id: "padded_leather_cape", name: "Padded Leather Cape" },
  empire_lord_helmet: { id: "empire_lord_helmet", name: "Palatine Guard Helmet" },
  peaked_fur_hood: { id: "peaked_fur_hood", name: "Peaked Fur Hood" },
  peaked_helmet_over_laced_coif: { id: "peaked_helmet_over_laced_coif", name: "Peaked Helmet over Laced Coif" },
  peaked_helmet_over_mail: { id: "peaked_helmet_over_mail", name: "Peaked Helmet over Mail" },
  peaked_helmet_over_mail_coif: { id: "peaked_helmet_over_mail_coif", name: "Peaked Helmet over Mail Coif" },
  peaked_helmet_over_padded_cloth: { id: "peaked_helmet_over_padded_cloth", name: "Peaked Helmet over Padded Cloth" },
  head_wrapping: { id: "head_wrapping", name: "Peasant Head Wrapping", civilian: true  },
  pilgrim_hood: { id: "pilgrim_hood", name: "Pilgrim Hood", civilian: true  },
  vlandia_lord_helmet_b2: { id: "vlandia_lord_helmet_b2", name: "Plated Helmet" },
  western_plated_helmet: { id: "western_plated_helmet", name: "Plated Helmet with Sideguards" },
  sturgian_lord_helmet_c: { id: "sturgian_lord_helmet_c", name: "Plated Warlord Helmet" },
  closed_goggled_helmet: { id: "closed_goggled_helmet", name: "Plumed Closed Warlord Helmet" },
  sturgian_helmet_b_open: { id: "sturgian_helmet_b_open", name: "Plumed Decorated Mailed Nasal Helmet" },
  plumed_fur_lined_helmet: { id: "plumed_fur_lined_helmet", name: "Plumed Fur Lined Helmet" },
  plumed_helmet: { id: "plumed_helmet", name: "Plumed Helmet" },
  plumed_lamellar_helmet: { id: "plumed_lamellar_helmet", name: "Plumed Lamellar Helmet" },
  plumed_nomad_helmet: { id: "plumed_nomad_helmet", name: "Plumed Nomad Helmet" },
  pointed_skullcap_over_cloth_headwrap: { id: "pointed_skullcap_over_cloth_headwrap", name: "Pointed Skullcap over Cloth Headwrap" },
  pointed_skullcap_over_mail: { id: "pointed_skullcap_over_mail", name: "Pointed Skullcap over Gambeson" },
  pointed_skullcap_over_laced_coif: { id: "pointed_skullcap_over_laced_coif", name: "Pointed Skullcap over Laced Coif" },
  pointed_skullcap_over_mail_coif: { id: "pointed_skullcap_over_mail_coif", name: "Pointed Skullcap over Mail Coif" },
  pointed_skullcap_with_mail: { id: "pointed_skullcap_with_mail", name: "Pointed Skullcap with Mail" },
  decorated_goggled_helmet: { id: "decorated_goggled_helmet", name: "Reinforced Closed Goggled Helmet" },
  battania_earmuff_helmet_d_brnz: { id: "battania_earmuff_helmet_d_brnz", name: "Ridged Decorated Bronze Cap with Cheek Guards" },
  battania_earmuff_helmet_d: { id: "battania_earmuff_helmet_d", name: "Ridged Decorated Steel Cap with Cheek Guards" },
  ridged_northernhelm: { id: "ridged_northernhelm", name: "Ridged Helm" },
  sturgian_lord_helmet_a: { id: "sturgian_lord_helmet_a", name: "Ridged Warlord Helmet" },
  vlandia_bandit_cape_a: { id: "vlandia_bandit_cape_a", name: "Rough Padded Cap" },
  roughhide_cap: { id: "roughhide_cap", name: "Roughhide Cap", civilian: true  },
  roughscale_helmet: { id: "roughscale_helmet", name: "Roughscale Helmet" },
  aserai_civil_hscarf_b: { id: "aserai_civil_hscarf_b", name: "Roughspun Kefiyyeh", civilian: true  },
  leatherlame_roundkettle: { id: "leatherlame_roundkettle", name: "Roundkettle Helmet" },
  roundkettle_over_imperial_cloth: { id: "roundkettle_over_imperial_cloth", name: "Roundkettle over Cloth" },
  roundkettle_over_laced_cloth: { id: "roundkettle_over_laced_cloth", name: "Roundkettle over Laced Cloth" },
  leatherlame_roundkettle_over_imperial_leather: { id: "leatherlame_roundkettle_over_imperial_leather", name: "Roundkettle over Leather" },
  roundkettle_over_imperial_mail: { id: "roundkettle_over_imperial_mail", name: "Roundkettle over Mail" },
  leatherlame_roundkettle_over_imperial_mail: { id: "leatherlame_roundkettle_over_imperial_mail", name: "Roundkettle over Mail" },
  roundkettle_over_imperial_padding: { id: "roundkettle_over_imperial_padding", name: "Roundkettle over Padding" },
  empire_guarded_lord_helmet: { id: "empire_guarded_lord_helmet", name: "Royal Cataphract Helmet" },
  womens_headwrap_c: { id: "womens_headwrap_c", name: "Rural Head Wrap", civilian: true  },
  aserai_villager_female_headdress: { id: "aserai_villager_female_headdress", name: "Rural Headdress", civilian: true  },
  northern_goggled_helmet: { id: "northern_goggled_helmet", name: "Sea Raider Goggled Helmet" },
  segmented_cervelliere_over_padded_cloth: { id: "segmented_cervelliere_over_padded_cloth", name: "Segmented Cervelliere over Padded Cloth" },
  segmented_cervelliere_over_laced_coif: { id: "segmented_cervelliere_over_laced_coif", name: "Segmented Cevelliere over Laced Coif" },
  segmented_cervelliere_over_mail: { id: "segmented_cervelliere_over_mail", name: "Segmented Cevelliere over Mail" },
  segmented_cervelliere_over_mail_coif: { id: "segmented_cervelliere_over_mail_coif", name: "Segmented Cevelliere over Mail Coif" },
  segmented_skullcap_over_laced_coif: { id: "segmented_skullcap_over_laced_coif", name: "Segmented Skullcap over Laced Coif" },
  segmented_skullcap_over_mail_coif: { id: "segmented_skullcap_over_mail_coif", name: "Segmented Skullcap over Mail Coif" },
  segmented_skullcap_over_padded_cloth: { id: "segmented_skullcap_over_padded_cloth", name: "Segmented Skullcap over Padded Cloth" },
  segmented_skullcap_over_padded_coif: { id: "segmented_skullcap_over_padded_coif", name: "Segmented Skullcap over Padded Coif" },
  leatherlame_feathered_spangenhelm_over_leather: { id: "leatherlame_feathered_spangenhelm_over_leather", name: "Spangenhelm over Leather" },
  ironlame_feathered_spangenhelm_over_mail: { id: "ironlame_feathered_spangenhelm_over_mail", name: "Spangenhelm over Mail" },
  spangenhelm_with_leather: { id: "spangenhelm_with_leather", name: "Spangenhelm with Leather" },
  spangenhelm_with_padded_cloth: { id: "spangenhelm_with_padded_cloth", name: "Spangenhelm with Padded Cloth" },
  spiked_helmet: { id: "spiked_helmet", name: "Spiked Helmet" },
  closed_desert_helmet: { id: "closed_desert_helmet", name: "Spiked Helmet with Closed Turban" },
  spiked_helmet_with_facemask: { id: "spiked_helmet_with_facemask", name: "Spiked Helmet with Facemask" },
  open_desert_helmet: { id: "open_desert_helmet", name: "Spiked Helmet with Open Turban" },
  spiked_kettle_over_imperial_mail: { id: "spiked_kettle_over_imperial_mail", name: "Spiked Kettle over Mail" },
  spiked_kettle_over_imperial_padding: { id: "spiked_kettle_over_imperial_padding", name: "Spiked Kettle over Padding" },
  desert_helmet: { id: "desert_helmet", name: "Steel Cap" },
  battania_earmuff_helmet_b: { id: "battania_earmuff_helmet_b", name: "Steel Cap with Cheek Guards" },
  nasal_helmet: { id: "nasal_helmet", name: "Steel Cap with Nose Guard" },
  sturgian_helmet_base: { id: "sturgian_helmet_base", name: "Steel Nasal Cap" },
  aserai_lord_helmet_a: { id: "aserai_lord_helmet_a", name: "Sultans' Crowned Lord Helmet" },
  southern_noble_helmet: { id: "southern_noble_helmet", name: "Sultans' Steel Cap" },
  tall_helmet: { id: "tall_helmet", name: "Tall Helmet" },
  fur_hood: { id: "fur_hood", name: "Thick Fur Hood" },
  thinhide_coif: { id: "thinhide_coif", name: "Thinhide Coif", civilian: true  },
  tied_head_wrapping: { id: "tied_head_wrapping", name: "Tied Head Wrapping", civilian: true  },
  tight_head_scarf: { id: "tight_head_scarf", name: "Tight Head Scarf" },
  tuareg: { id: "tuareg", name: "Tribal Turban", civilian: true  },
  turban: { id: "turban", name: "Turban", civilian: true  },
  battania_battle_crown: { id: "battania_battle_crown", name: "Two Pronged Bronze Crown", civilian: true  },
  upturned_fur_cap: { id: "upturned_fur_cap", name: "Upturned Fur Cap", civilian: true  },
  visored_helmet_over_laced_coif: { id: "visored_helmet_over_laced_coif", name: "Visored Helmet over Laced Coif" },
  visored_helmet_over_mail_coif: { id: "visored_helmet_over_mail_coif", name: "Visored Helmet over Mail Coif" },
  visored_helmet_over_padded_cloth: { id: "visored_helmet_over_padded_cloth", name: "Visored Helmet over Padded Cloth" },
  visored_helmet_over_padded_coif: { id: "visored_helmet_over_padded_coif", name: "Visored Helmet over Padded Coif" },
  battanian_noble_helmet_with_feather: { id: "battanian_noble_helmet_with_feather", name: "Warlord Helmet" },
  lendman_helmet_over_full_mail: { id: "lendman_helmet_over_full_mail", name: "Warlord Helmet over Full Mail" },
  lendman_helmet_over_mail: { id: "lendman_helmet_over_mail", name: "Warlord Helmet over Mail" },
  northern_warlord_helmet: { id: "northern_warlord_helmet", name: "Warlord Helmet with Cheek Guards" },
  battanian_plated_noble_helmet: { id: "battanian_plated_noble_helmet", name: "Warlord Helmet with Feather" },
  sturgian_lord_helmet_b: { id: "sturgian_lord_helmet_b", name: "Warlord Helmet with Nose Guard" },
  wolfhead: { id: "wolfhead", name: "Wolf Head" },
  woven_turban: { id: "woven_turban", name: "Woven Turban", civilian: true  },
  desert_cap: { id: "desert_cap", name: "Wrapped Cap", civilian: true  },
  wrapped_headcloth: { id: "wrapped_headcloth", name: "Wrapped Headcloth", civilian: true  },
  desert_mail_coif: { id: "desert_mail_coif", name: "Wrapped Helmet with Mail Coif" },
  wrapped_desert_cap: { id: "wrapped_desert_cap", name: "Wrapped Leather Cap", civilian: true  },
};

export const CAPES: Record<string, Item> = {
  armored_bearskin: { id: "armored_bearskin", name: "Armored Bearskin" },
  bearskin: { id: "bearskin", name: "Bear Pelt" },
  bolted_leather_strips: { id: "bolted_leather_strips", name: "Bolted Leather Strips" },
  a_aserai_scale_b_shoulder_d: { id: "a_aserai_scale_b_shoulder_d", name: "Brass Scale Pauldrons" },
  a_brass_lamellar_shoulder_a: { id: "a_brass_lamellar_shoulder_a", name: "Bronze Lamellar Shoulder Guards" },
  brass_lamellar_shoulder: { id: "brass_lamellar_shoulder", name: "Bronze Lamellar Shoulder Pieces" },
  a_pauldron_cape_c: { id: "a_pauldron_cape_c", name: "Bronze Pauldrons" },
  a_pauldron_cape_b: { id: "a_pauldron_cape_b", name: "Bronze Pauldrons with Neck Guard" },
  empire_plate_armor_shoulder_a: { id: "empire_plate_armor_shoulder_a", name: "Bronze Plate Pouldrons" },
  a_aserai_scale_b_shoulder_c: { id: "a_aserai_scale_b_shoulder_c", name: "Bronze Scale Shoulder Guards" },
  brass_scale_shoulders: { id: "brass_scale_shoulders", name: "Bronze Scale Shoulder Guards" },
  battania_cloak_furr: { id: "battania_cloak_furr", name: "Chained Fur Cloak" },
  steppe_leather_shoulders: { id: "steppe_leather_shoulders", name: "Cured Leather Pouldrons" },
  battanian_leather_shoulder_a: { id: "battanian_leather_shoulder_a", name: "Cured Leather Shoulder Pieces" },
  a_khuzait_leather_shoulder_b_a: { id: "a_khuzait_leather_shoulder_b_a", name: "Cured Studded Leather Armor" },
  a_leather_lamellar_armor_shoulder_a: { id: "a_leather_lamellar_armor_shoulder_a", name: "Decorated Lamellar Leather Shoulder Guards" },
  a_metal_lamellar_armor_shoulder_a: { id: "a_metal_lamellar_armor_shoulder_a", name: "Decorated Steel Lamellar Shoulder Pieces" },
  battania_civil_cloak: { id: "battania_civil_cloak", name: "Fringed Cloak" },
  green_hood: { id: "green_hood", name: "Green Hood", civilian: true  },
  imperial_lamellar_shoulders: { id: "imperial_lamellar_shoulders", name: "Heavy Lamellar Pouldrons" },
  battania_scarf_a: { id: "battania_scarf_a", name: "Heavy Tartan Cape" },
  battania_warlord_pauldrons: { id: "battania_warlord_pauldrons", name: "Heavy Warlord Pauldrons" },
  hood: { id: "hood", name: "Hood", civilian: true  },
  empire_plate_armor_shoulder_b: { id: "empire_plate_armor_shoulder_b", name: "Iron Plate Pouldrons" },
  brass_lamellar_shoulder_white: { id: "brass_lamellar_shoulder_white", name: "Lamellar Pauldrons" },
  a_brass_lamellar_shoulder_white_a: { id: "a_brass_lamellar_shoulder_white_a", name: "Lamellar Shoulder Guards" },
  lamellar_shoulders: { id: "lamellar_shoulders", name: "Lamellar Shoulder Pieces" },
  leather_lamellar_shoulders: { id: "leather_lamellar_shoulders", name: "Leather Lamellar Shoulder Guards" },
  desert_leather_shoulderpad: { id: "desert_leather_shoulderpad", name: "Leather Shoulder Guard" },
  pauldron_cape_a: { id: "pauldron_cape_a", name: "Legionary Cape" },
  empire_warrior_padded_armor_shoulder: { id: "empire_warrior_padded_armor_shoulder", name: "Legionary Padded Straps" },
  imperial_studded_strip_shoulders: { id: "imperial_studded_strip_shoulders", name: "Legionary Reinforced Studded Harness" },
  a_empire_plated_shoulder_a: { id: "a_empire_plated_shoulder_a", name: "Legionary Studded Harness" },
  leopard_pelt: { id: "leopard_pelt", name: "Leopard Pelt" },
  mail_shoulders: { id: "mail_shoulders", name: "Mail Shoulder Guards" },
  battanian_chainmail_shoulder_a: { id: "battanian_chainmail_shoulder_a", name: "Mail Shoulder Pieces" },
  battanian_chainmail_shoulder_b: { id: "battanian_chainmail_shoulder_b", name: "Mail Shoulder Reinforcements" },
  studded_imperial_neckguard: { id: "studded_imperial_neckguard", name: "Neckguard with Bronze Plate Pouldrons" },
  padded_leather_shoulders: { id: "padded_leather_shoulders", name: "Padded Leather Shoulders" },
  a_empire_plated_shoulder_b: { id: "a_empire_plated_shoulder_b", name: "Plate Pauldrons" },
  a_aserai_scale_b_shoulder_e: { id: "a_aserai_scale_b_shoulder_e", name: "Reinforced Bronze Scale Shoulder Guards" },
  battania_shoulder_furr: { id: "battania_shoulder_furr", name: "Reinforced Harness with Cape" },
  a_brass_lamellar_shoulder_b: { id: "a_brass_lamellar_shoulder_b", name: "Reinforced Lamellar Shoulder Guards" },
  a_brass_lamellar_shoulder_white_b: { id: "a_brass_lamellar_shoulder_white_b", name: "Reinforced Lamellar Shoulder Guards" },
  khuzait_leather_pauldron: { id: "khuzait_leather_pauldron", name: "Reinforced Leather Pauldrons" },
  desert_scale_shoulders: { id: "desert_scale_shoulders", name: "Reinforced Scale Pouldrons" },
  a_khuzait_leather_shoulder_b_b: { id: "a_khuzait_leather_shoulder_b_b", name: "Reinforced Studded Neckguard" },
  eastern_studded_shoulders: { id: "eastern_studded_shoulders", name: "Reinforced Studded Shoulder Guards" },
  reinforced_suede_shoulders: { id: "reinforced_suede_shoulders", name: "Reinforced Suede Shoulder Guards" },
  aserai_horseman_shoulder: { id: "aserai_horseman_shoulder", name: "Ringmail Shoulder Guard" },
  rough_bearskin: { id: "rough_bearskin", name: "Rough Bearskin" },
  a_aserai_scale_b_shoulder_b: { id: "a_aserai_scale_b_shoulder_b", name: "Scale Pauldrons" },
  a_aserai_scale_b_shoulder_a: { id: "a_aserai_scale_b_shoulder_a", name: "Scale Shoulder Guards" },
  scarf: { id: "scarf", name: "Scarf", civilian: true  },
  wrapped_scarf: { id: "wrapped_scarf", name: "Shawl", civilian: true  },
  southern_shawl: { id: "southern_shawl", name: "Short Cloak", civilian: true  },
  battania_shoulder_strap: { id: "battania_shoulder_strap", name: "Shoulder Harness" },
  a_battania_cloak_a: { id: "a_battania_cloak_a", name: "Simple Cape", civilian: true  },
  stitched_leather_shoulders: { id: "stitched_leather_shoulders", name: "Stitched Leather Shoulders" },
  battania_cloak_b: { id: "battania_cloak_b", name: "Tartan Cape" },
  battania_cloak: { id: "battania_cloak", name: "Tartan Cloak", civilian: true  },
  battania_shoulder_strap_cloak: { id: "battania_shoulder_strap_cloak", name: "Tartan Shoulder Harness" },
  wolf_shoulder: { id: "wolf_shoulder", name: "Wolf Pelt Cape" },
  female_hood: { id: "female_hood", name: "Woman's Hood", civilian: true  },
  female_scarf: { id: "female_scarf", name: "Woman's Scarf", civilian: true  },
  battania_woodland_cloak: { id: "battania_woodland_cloak", name: "Woodland Cloak" },
  battania_civil_cape: { id: "battania_civil_cape", name: "Woodland Fur Cape" },
  woven_leather_shoulders: { id: "woven_leather_shoulders", name: "Woven Leather Shoulders" },
  desert_fabric_shoulderpad: { id: "desert_fabric_shoulderpad", name: "Woven Shoulder Pad", civilian: true  },
};

export const BODY_ARMORS: Record<string, Item> = {
  aketon: { id: "aketon", name: "Aketon" },
  vlandian_woman_dress: { id: "vlandian_woman_dress", name: "Aproned Dress", civilian: true  },
  khuzait_dress: { id: "khuzait_dress", name: "Aproned Feminine Coat", civilian: true  },
  armored_baggy_trunks: { id: "armored_baggy_trunks", name: "Armored Baggy Trunks" },
  aserai_armor_02: { id: "aserai_armor_02", name: "Aserai Chain Mail" },
  aserai_armor_02_b: { id: "aserai_armor_02_b", name: "Aserai Decorated Chain Mail" },
  empire_warrior_padded_armor_f: { id: "empire_warrior_padded_armor_f", name: "Auxiliary Armor" },
  empire_warrior_padded_armor_g: { id: "empire_warrior_padded_armor_g", name: "Auxiliary Armor with Straps" },
  baggy_trunks: { id: "baggy_trunks", name: "Baggy Trunks" },
  banded_leather_over_mail: { id: "banded_leather_over_mail", name: "Banded Leather over Mail" },
  battania_light_armor_b: { id: "battania_light_armor_b", name: "Battanian Tartan" },
  battania_light_armor_a: { id: "battania_light_armor_a", name: "Battanian Tartan with Chest Plate" },
  belted_leather_cuirass: { id: "belted_leather_cuirass", name: "Belted Leather Cuirass" },
  tundra_tunic: { id: "tundra_tunic", name: "Belted Tunic", civilian: true  },
  woven_leather_coat: { id: "woven_leather_coat", name: "Boarskin Leather Coat" },
  sturgian_fortified_armor: { id: "sturgian_fortified_armor", name: "Brigandine over Hauberk" },
  coat_of_plates_over_mail: { id: "coat_of_plates_over_mail", name: "Brigandine over Mail" },
  eastern_plated_leather_vest: { id: "eastern_plated_leather_vest", name: "Brigandine Vest" },
  brass_lamellar_over_mail: { id: "brass_lamellar_over_mail", name: "Bronze Lamellar over Mail" },
  southern_lamellar_armor: { id: "southern_lamellar_armor", name: "Bronze Lamellar Vest over Gambeson" },
  nordic_lamellar_vest: { id: "nordic_lamellar_vest", name: "Bronze Scale Vest" },
  nordic_lamellar_armor: { id: "nordic_lamellar_armor", name: "Bronze Scale Vest over Gambeson" },
  buckled_wildsman_armor: { id: "buckled_wildsman_armor", name: "Buckled Mail Armor" },
  burlap_sack_dress: { id: "burlap_sack_dress", name: "Burlap Dress", civilian: true  },
  burlap_waistcoat: { id: "burlap_waistcoat", name: "Burlap Waistcoat", civilian: true  },
  imperial_lamellar: { id: "imperial_lamellar", name: "Cataphract Lamellar Armor" },
  sturgia_cavalry_armor: { id: "sturgia_cavalry_armor", name: "Cavalry Lamellar Armor" },
  empire_horseman_armor: { id: "empire_horseman_armor", name: "Cavalryman Mail Shirt" },
  vlandia_bandit_b: { id: "vlandia_bandit_b", name: "Cheap Colored Clothes" },
  vlandia_bandit_a: { id: "vlandia_bandit_a", name: "Cheap Paddings" },
  cloth_apron: { id: "cloth_apron", name: "Cloth Apron", civilian: true  },
  northern_coat_of_plates: { id: "northern_coat_of_plates", name: "Coat Of Plates" },
  khuzait_belt_leather: { id: "khuzait_belt_leather", name: "Coat with Mirrored Belt", civilian: true  },
  northern_dress: { id: "northern_dress", name: "Cold Weather Dress", civilian: true  },
  aserai_civil_d: { id: "aserai_civil_d", name: "Colored Bisht", civilian: true  },
  aserai_civil_c: { id: "aserai_civil_c", name: "Colored Kaftan", civilian: true  },
  peasant_costume: { id: "peasant_costume", name: "Commoner Clothes", civilian: true  },
  bandit_leather_water_flask: { id: "bandit_leather_water_flask", name: "Commoner Shirt", civilian: true  },
  bandit_envelope_dress_v1: { id: "bandit_envelope_dress_v1", name: "Commoner Tunic", civilian: true  },
  vlandian_corset_dress: { id: "vlandian_corset_dress", name: "Corseted Dress", civilian: true  },
  crude_leather_armor: { id: "crude_leather_armor", name: "Crude Hide Armor" },
  leather_lamellar_armor: { id: "leather_lamellar_armor", name: "Cured Leather Lamellar Armor" },
  northern_lamellar_armor: { id: "northern_lamellar_armor", name: "Cured Leather Lamellar Shirt" },
  eastern_studded_leather: { id: "eastern_studded_leather", name: "Cured Studded Leather Armor" },
  cut_dress_with_pouch: { id: "cut_dress_with_pouch", name: "Cut Dress with Pouch", civilian: true  },
  sturgian_chainmale_longsleeve: { id: "sturgian_chainmale_longsleeve", name: "Decorated Hauberk" },
  decorated_short_tunic: { id: "decorated_short_tunic", name: "Decorated Thick Tunic", civilian: true  },
  dress_with_overall: { id: "dress_with_overall", name: "Dress", civilian: true  },
  khuzait_dress_b: { id: "khuzait_dress_b", name: "Dress with Fur", civilian: true  },
  dummy_armor_higher_average: { id: "dummy_armor_higher_average", name: "Dummy Higher Average" },
  dummy_armor_lower_average: { id: "dummy_armor_lower_average", name: "Dummy Lower Average" },
  dummy_armor_max: { id: "dummy_armor_max", name: "Dummy Max Armor" },
  dummy_armor_min: { id: "dummy_armor_min", name: "Dummy Min Armor" },
  steppe_dress: { id: "steppe_dress", name: "Envelope Dress", civilian: true  },
  aserai_female_civil_a: { id: "aserai_female_civil_a", name: "Feminine Kaftan", civilian: true  },
  padded_coat: { id: "padded_coat", name: "Footmans Padded Coat" },
  veteran_mercenary_armor: { id: "veteran_mercenary_armor", name: "Fortified Mercenary Armor" },
  cut_dress: { id: "cut_dress", name: "Frilled Dress", civilian: true  },
  fur_armor: { id: "fur_armor", name: "Fur Armor" },
  fur_armor_with_strap: { id: "fur_armor_with_strap", name: "Fur Armor with Strap", civilian: true  },
  fur_coat_over_tunic: { id: "fur_coat_over_tunic", name: "Fur Coat over Tunic" },
  fur_skirt: { id: "fur_skirt", name: "Fur Skirt" },
  fur_skirt_with_tunic: { id: "fur_skirt_with_tunic", name: "Fur Skirt with Tunic" },
  fur_trimmed_short_tunic: { id: "fur_trimmed_short_tunic", name: "Fur Trimmed Short Tunic", civilian: true  },
  fur_trimmed_tunic: { id: "fur_trimmed_tunic", name: "Fur Trimmed Tunic", civilian: true  },
  fur_waistcoat_over_tunic: { id: "fur_waistcoat_over_tunic", name: "Fur Waistcoat over Tunic" },
  aserai_archer_armor: { id: "aserai_archer_armor", name: "Gambeson over Mail Armor" },
  half_apron: { id: "half_apron", name: "Half Apron", civilian: true  },
  gambeson_b: { id: "gambeson_b", name: "Heavy Aketon", civilian: true  },
  sturgian_lamellar_fortified: { id: "sturgian_lamellar_fortified", name: "Heavy Lamellar over Hauberk" },
  northern_brass_lamellar_over_mail: { id: "northern_brass_lamellar_over_mail", name: "Heavy Lamellar over Mail" },
  sturgian_lamellar_base: { id: "sturgian_lamellar_base", name: "Heavy Lamellar over Mail Armor" },
  sturgian_lamellar_gambeson_heavy: { id: "sturgian_lamellar_gambeson_heavy", name: "Heavy Lamellar Vest" },
  sturgian_lamellar_gambeson: { id: "sturgian_lamellar_gambeson", name: "Heavy Lamellar Vest" },
  vlandia_chainmail: { id: "vlandia_chainmail", name: "Heavy Mail Hauberk" },
  hauberk: { id: "hauberk", name: "Heavy Mail Shirt" },
  battania_woodland_chainmail: { id: "battania_woodland_chainmail", name: "Heavy Mail Shirt with Wide Belt" },
  battanian_chainmail_armor_a: { id: "battanian_chainmail_armor_a", name: "Heavy Mail Vest" },
  ringed_desert_armor: { id: "ringed_desert_armor", name: "Heavy Ring Mail" },
  imperial_scale_armor: { id: "imperial_scale_armor", name: "Heavy Scale Armor over Mail Hauberk" },
  heavy_nordic_tunic: { id: "heavy_nordic_tunic", name: "Heavy Tunic", civilian: true  },
  hemp_tunic: { id: "hemp_tunic", name: "Hemp Tunic", civilian: true  },
  battania_noble_armor: { id: "battania_noble_armor", name: "Highborn Mail Armor" },
  battanian_chainmail_armor_b: { id: "battanian_chainmail_armor_b", name: "Highland Mail Shirt" },
  battanian_chainmail_armor_d: { id: "battanian_chainmail_armor_d", name: "Highland Reinforced Fian Mail" },
  battanian_chainmail_armor_c: { id: "battanian_chainmail_armor_c", name: "Highland Reinforced Mail over Tartan" },
  battanian_scale_armor_b: { id: "battanian_scale_armor_b", name: "Highland Scale Armor over Cloth" },
  battanian_scale_armor_a: { id: "battanian_scale_armor_a", name: "Highland Scale Armor over Mail Armor" },
  decorated_nordic_hauberk: { id: "decorated_nordic_hauberk", name: "Huscarls Decorated Mail Shirt" },
  sturgian_chainmale_shortsleeve: { id: "sturgian_chainmale_shortsleeve", name: "Huscarls Hauberk" },
  nordic_hauberk: { id: "nordic_hauberk", name: "Huscarls Mail Shirt" },
  empire_warrior_padded_armor_a: { id: "empire_warrior_padded_armor_a", name: "Infantryman Gambeson", civilian: true  },
  empire_warrior_padded_armor_b: { id: "empire_warrior_padded_armor_b", name: "Infantryman Gambeson over Leather Jacket", civilian: true  },
  empire_warrior_padded_armor_c: { id: "empire_warrior_padded_armor_c", name: "Infantryman Gambeson with Skirts", civilian: true  },
  empire_warrior_padded_armor_d: { id: "empire_warrior_padded_armor_d", name: "Infantryman Gambeson with Straps", civilian: true  },
  empire_warrior_padded_armor_e: { id: "empire_warrior_padded_armor_e", name: "Infantryman Long Gambeson", civilian: true  },
  imperial_mail_over_leather: { id: "imperial_mail_over_leather", name: "Infantryman Mail over Leather" },
  imperial_mail_over_stripped_leather: { id: "imperial_mail_over_stripped_leather", name: "Infantryman Mail over Striped Leather" },
  imperial_mail_vest: { id: "imperial_mail_vest", name: "Infantryman Mail Vest" },
  imperial_padded_cloth: { id: "imperial_padded_cloth", name: "Infantryman Rough Gambeson", civilian: true  },
  aserai_civil_b: { id: "aserai_civil_b", name: "Kaftan with Leather Belt", civilian: true  },
  aserai_female_civil_b: { id: "aserai_female_civil_b", name: "Kaftan with Waistband", civilian: true  },
  kilt_over_plated_leather: { id: "kilt_over_plated_leather", name: "Kilt over Plated Leather" },
  laced_dress: { id: "laced_dress", name: "Laced Dress", civilian: true  },
  empire_dress: { id: "empire_dress", name: "Ladies Dress", civilian: true  },
  lamellar_with_scale_skirt: { id: "lamellar_with_scale_skirt", name: "Lamellar with Scale Skirt" },
  eastern_lamellar_armor: { id: "eastern_lamellar_armor", name: "Lancer Lamellar Armor" },
  layered_leather_tunic: { id: "layered_leather_tunic", name: "Layered Leather Tunic", civilian: true  },
  layered_robe: { id: "layered_robe", name: "Layered Robe", civilian: true  },
  leather_apron: { id: "leather_apron", name: "Leather Apron", civilian: true  },
  basic_imperial_leather_armor: { id: "basic_imperial_leather_armor", name: "Leather Armor" },
  nordic_sloven: { id: "nordic_sloven", name: "Leather Armor over Heavy Cloth", civilian: true  },
  leather_and_iron_plate_armor: { id: "leather_and_iron_plate_armor", name: "Leather Armor with Iron Plates" },
  leather_coat_over_cloth: { id: "leather_coat_over_cloth", name: "Leather Coat over Cloth", civilian: true  },
  leather_scale_armor: { id: "leather_scale_armor", name: "Leather Scale Armor", civilian: true  },
  leather_strips_over_padded_robe: { id: "leather_strips_over_padded_robe", name: "Leather Strips over Padded Robe", civilian: true  },
  northern_leather_tabard: { id: "northern_leather_tabard", name: "Leather Tabard" },
  nordic_sloven_over_mail: { id: "nordic_sloven_over_mail", name: "Leather Tabard over Mail" },
  leather_coat: { id: "leather_coat", name: "Leather Tunic", civilian: true  },
  leather_tunic: { id: "leather_tunic", name: "Leather Tunic", civilian: true  },
  legionary_mail: { id: "legionary_mail", name: "Legionary Mail" },
  desert_lamellar: { id: "desert_lamellar", name: "Light Lamellar Armor" },
  desert_padded_cloth: { id: "desert_padded_cloth", name: "Light Long Padded Armor", civilian: true  },
  northern_padded_cloth: { id: "northern_padded_cloth", name: "Light Padded Armor", civilian: true  },
  light_tunic: { id: "light_tunic", name: "Light Tunic", civilian: true  },
  long_fur_coat: { id: "long_fur_coat", name: "Long Fur Coat", civilian: true  },
  long_hemp_tunic: { id: "long_hemp_tunic", name: "Long Hemp Tunic", civilian: true  },
  long_padded_robe: { id: "long_padded_robe", name: "Long Padded Robe", civilian: true  },
  long_desert_robe: { id: "long_desert_robe", name: "Long Simple Robe", civilian: true  },
  sturgia_light_tunic: { id: "sturgia_light_tunic", name: "Long Tunic", civilian: true  },
  long_woolen_tunic: { id: "long_woolen_tunic", name: "Long Woolen Tunic", civilian: true  },
  battania_mercenary_armor: { id: "battania_mercenary_armor", name: "Luxury Brigandine" },
  khuzait_civil_coat: { id: "khuzait_civil_coat", name: "Luxury Coat", civilian: true  },
  aserai_tunic_waistcoat: { id: "aserai_tunic_waistcoat", name: "Luxury Kaftan", civilian: true  },
  aserai_civil_a: { id: "aserai_civil_a", name: "Luxury Kaftan with Waistband", civilian: true  },
  imperial_lamellar_over_leather: { id: "imperial_lamellar_over_leather", name: "Luxury Lamellar Vest over Leather" },
  desert_scale_armor: { id: "desert_scale_armor", name: "Luxury Scale Armor" },
  khuzait_civil_coat_b: { id: "khuzait_civil_coat_b", name: "Luxury Thick Coat", civilian: true  },
  nordic_tunic: { id: "nordic_tunic", name: "Luxury Tunic", civilian: true  },
  mail_shirt: { id: "mail_shirt", name: "Mail Shirt" },
  merchants_fur_coat: { id: "merchants_fur_coat", name: "Merchant Fur Coat", civilian: true  },
  footmans_tunic: { id: "footmans_tunic", name: "Military Tunic", civilian: true  },
  eastern_plated_leather: { id: "eastern_plated_leather", name: "Mirrored Brigandine Armor" },
  khuzait_sturdy_armor: { id: "khuzait_sturdy_armor", name: "Mirrored Leather Armor" },
  bandit_fur_a: { id: "bandit_fur_a", name: "Old Fur Armor", civilian: true  },
  bandit_fur_b: { id: "bandit_fur_b", name: "Old Fur Coat", civilian: true  },
  padded_cloth_with_strips: { id: "padded_cloth_with_strips", name: "Padded Cloth with Strips" },
  padded_leather_overcoat: { id: "padded_leather_overcoat", name: "Padded Leather Overcoat" },
  padded_leather_shirt: { id: "padded_leather_shirt", name: "Padded Leather Shirt", civilian: true  },
  padded_short_coat: { id: "padded_short_coat", name: "Padded Short Coat" },
  patched_gambeson: { id: "patched_gambeson", name: "Patched Gambeson", civilian: true  },
  battania_dress_a: { id: "battania_dress_a", name: "Plaid Dress", civilian: true  },
  plain_dress: { id: "plain_dress", name: "Plain Dress", civilian: true  },
  ragged_robes: { id: "ragged_robes", name: "Ragged Robes", civilian: true  },
  ranger_mail: { id: "ranger_mail", name: "Ranger Mail" },
  empire_dress_b: { id: "empire_dress_b", name: "Red Dress", civilian: true  },
  red_coat_over_mail: { id: "red_coat_over_mail", name: "Red Tabard over Mail Hauberk" },
  khuzait_lamellar_strapped: { id: "khuzait_lamellar_strapped", name: "Reinforced Leather Armor" },
  khuzait_fortified_armor: { id: "khuzait_fortified_armor", name: "Reinforced Mirror Armor", civilian: true  },
  reinforced_suede_armor: { id: "reinforced_suede_armor", name: "Reinforced Suede Armor" },
  nordic_padded_cloth: { id: "nordic_padded_cloth", name: "Reinforced Thick Tunic", civilian: true  },
  vlandian_dress: { id: "vlandian_dress", name: "Rich Dress", civilian: true  },
  fine_town_tunic: { id: "fine_town_tunic", name: "Rich Tunic", civilian: true  },
  aserai_horseman_armor: { id: "aserai_horseman_armor", name: "Ring Mail" },
  desert_robe_over_mail: { id: "desert_robe_over_mail", name: "Robe over Mail Hauberk" },
  aserai_robe_c_chain: { id: "aserai_robe_c_chain", name: "Robe over Mail Shirt" },
  plated_leather_coat: { id: "plated_leather_coat", name: "Rough Brigandine" },
  rough_fur_armor: { id: "rough_fur_armor", name: "Rough Fur Armor" },
  rough_fur_over_chain: { id: "rough_fur_over_chain", name: "Rough Fur over Mail" },
  western_scale_mail: { id: "western_scale_mail", name: "Rough Scale Mail" },
  roughcloth_shortcoat: { id: "roughcloth_shortcoat", name: "Roughcloth Shortcoat", civilian: true  },
  bandit_gambeson: { id: "bandit_gambeson", name: "Rugged Gambeson", civilian: true  },
  scale_armor: { id: "scale_armor", name: "Rugged Scale Armor" },
  sackcloth_tunic: { id: "sackcloth_tunic", name: "Sackcloth Tunic", civilian: true  },
  monk_robe: { id: "monk_robe", name: "Scholar Robe", civilian: true  },
  northern_padded_gambeson: { id: "northern_padded_gambeson", name: "Short Gambeson over Tunic", civilian: true  },
  short_padded_robe: { id: "short_padded_robe", name: "Short Padded Robe", civilian: true  },
  empire_short_dress: { id: "empire_short_dress", name: "Short Tunic", civilian: true  },
  eastern_silk_clothing: { id: "eastern_silk_clothing", name: "Silk Kaftan", civilian: true  },
  vlandian_noble_woman_dress: { id: "vlandian_noble_woman_dress", name: "Silken Noble Dress", civilian: true  },
  cloth_tunic: { id: "cloth_tunic", name: "Simple Cloth Tunic", civilian: true  },
  desert_robe: { id: "desert_robe", name: "Simple Kaftan", civilian: true  },
  aserai_civil_f: { id: "aserai_civil_f", name: "Simple Peasant Robe", civilian: true  },
  heavy_nordic_coat: { id: "heavy_nordic_coat", name: "Sleeved Heavy Tunic", civilian: true  },
  bandit_envelope_dress_v2: { id: "bandit_envelope_dress_v2", name: "Sleeveless Enveloped Padded Garments", civilian: true  },
  sleeveless_fur_coat: { id: "sleeveless_fur_coat", name: "Sleeveless Fur Coat" },
  sleeveless_padded_coat: { id: "sleeveless_padded_coat", name: "Sleeveless Padded Coat" },
  sleeveless_padded_short_coat: { id: "sleeveless_padded_short_coat", name: "Sleeveless Padded Short Coat", civilian: true  },
  sleeveless_studded_fur_armor: { id: "sleeveless_studded_fur_armor", name: "Sleeveless Studded Fur Armor", civilian: true  },
  nordic_sloven_leather: { id: "nordic_sloven_leather", name: "Sloven Leather" },
  steppe_robe: { id: "steppe_robe", name: "Steppe Robe", civilian: true  },
  eastern_stitched_leather_coat: { id: "eastern_stitched_leather_coat", name: "Stitched Cured Leather Coat" },
  stitched_leather_over_mail: { id: "stitched_leather_over_mail", name: "Stitched Leather over Mail" },
  stitched_leather_vest: { id: "stitched_leather_vest", name: "Stitched Leather Vest", civilian: true  },
  steppe_armor: { id: "steppe_armor", name: "Striped Coat", civilian: true  },
  studded_fur_armor: { id: "studded_fur_armor", name: "Studded Fur Armor" },
  studded_steppe_leather: { id: "studded_steppe_leather", name: "Studded Leather Armor" },
  studded_leather_coat: { id: "studded_leather_coat", name: "Studded Leather Coat" },
  studded_leather_over_aketon: { id: "studded_leather_over_aketon", name: "Studded Leather over Aketon" },
  studded_leather_waistcoat: { id: "studded_leather_waistcoat", name: "Studded Leather Waistcoat", civilian: true  },
  fine_southern_dress: { id: "fine_southern_dress", name: "Tailored Dress", civilian: true  },
  battania_female_civil_a: { id: "battania_female_civil_a", name: "Tartan Dress", civilian: true  },
  battania_dress_c: { id: "battania_dress_c", name: "Tartan Long Dress", civilian: true  },
  battania_civil_a: { id: "battania_civil_a", name: "Tartan Tunic", civilian: true  },
  tassled_southern_robes: { id: "tassled_southern_robes", name: "Tassled Robes", civilian: true  },
  tattered_rags: { id: "tattered_rags", name: "Tattered Rags", civilian: true  },
  aserai_civil_e: { id: "aserai_civil_e", name: "Thawb", civilian: true  },
  khuzait_leather_stitched: { id: "khuzait_leather_stitched", name: "Thick Brigandine Vest", civilian: true  },
  thick_sleeved_robe: { id: "thick_sleeved_robe", name: "Thick Sleeved Robe", civilian: true  },
  tied_cloth_tunic: { id: "tied_cloth_tunic", name: "Tied Cloth Tunic", civilian: true  },
  imperial_robes: { id: "imperial_robes", name: "Toga", civilian: true  },
  torn_bandit_clothes: { id: "torn_bandit_clothes", name: "Torn Padded Garments", civilian: true  },
  vlandia_bandit_c: { id: "vlandia_bandit_c", name: "Torn Robe" },
  battania_civil_c: { id: "battania_civil_c", name: "Townsman Luxury Coat", civilian: true  },
  northern_leather_vest: { id: "northern_leather_vest", name: "Tunic with Leather Vest", civilian: true  },
  tunic_with_rolled_cloth: { id: "tunic_with_rolled_cloth", name: "Tunic with Rolled Cloth", civilian: true  },
  tunic_with_shoulder_pads: { id: "tunic_with_shoulder_pads", name: "Tunic with Shoulder Pads" },
  northern_tunic: { id: "northern_tunic", name: "Varyag Tunic", civilian: true  },
  battania_civil_b: { id: "battania_civil_b", name: "Villager Leather Tunic", civilian: true  },
  aserai_villager_female_dress: { id: "aserai_villager_female_dress", name: "Villager Short Dress", civilian: true  },
  battania_female_civil_b: { id: "battania_female_civil_b", name: "Villager Thick Dress", civilian: true  },
  battania_warlord_armor: { id: "battania_warlord_armor", name: "Warlords Scale Armor" },
  white_coat_over_mail: { id: "white_coat_over_mail", name: "White Tabard over Mail Hauberk" },
  battanian_savage_armor: { id: "battanian_savage_armor", name: "Wildling Armor", civilian: true  },
  highland_cloth: { id: "highland_cloth", name: "Woodland Cloth Armor", civilian: true  },
  battania_dress_b: { id: "battania_dress_b", name: "Woodland Commoner Dress", civilian: true  },
  battania_woodland_outfit: { id: "battania_woodland_outfit", name: "Woodland Garments", civilian: true  },
  woven_leather_vest: { id: "woven_leather_vest", name: "Woven Leather Vest" },
};

export const HAND_ARMORS: Record<string, Item> = {
  armwraps: { id: "armwraps", name: "Armwraps", civilian: true  },
  northern_brass_bracers: { id: "northern_brass_bracers", name: "Bronze Bracers" },
  buttoned_leather_bracers: { id: "buttoned_leather_bracers", name: "Buttoned Leather Bracers", civilian: true  },
  decorated_imperial_gauntlets: { id: "decorated_imperial_gauntlets", name: "Decorated Imperial Gauntlets" },
  battania_noble_bracers: { id: "battania_noble_bracers", name: "Fian Bracers", civilian: true  },
  highland_gloves: { id: "highland_gloves", name: "Fur Rimmed Leather Gloves", civilian: true  },
  guarded_armwraps: { id: "guarded_armwraps", name: "Guarded Armwraps", civilian: true  },
  guarded_padded_vambrace: { id: "guarded_padded_vambrace", name: "Guarded Padded Vambraces", civilian: true  },
  lordly_mail_mitten: { id: "lordly_mail_mitten", name: "Heavy Mail Mittens" },
  lamellar_plate_gauntlets: { id: "lamellar_plate_gauntlets", name: "Lamellar Plate Gauntlets" },
  leather_gloves: { id: "leather_gloves", name: "Leather Gloves", civilian: true  },
  steppe_leather_vambraces: { id: "steppe_leather_vambraces", name: "Leather Vambraces", civilian: true  },
  lordly_padded_mitten: { id: "lordly_padded_mitten", name: "Lordly Padded Mittens" },
  mail_mitten: { id: "mail_mitten", name: "Mail Mittens" },
  padded_mitten: { id: "padded_mitten", name: "Padded Mittens", civilian: true  },
  padded_vambrace: { id: "padded_vambrace", name: "Padded Vambraces" },
  northern_plated_gloves: { id: "northern_plated_gloves", name: "Plate Reinforced Gloves" },
  eastern_plated_leather_vambraces: { id: "eastern_plated_leather_vambraces", name: "Plated Leather Vambraces" },
  plated_strip_gauntlets: { id: "plated_strip_gauntlets", name: "Plated Striped Gauntlets" },
  ragged_armwraps: { id: "ragged_armwraps", name: "Ragged Armwraps", civilian: true  },
  reinforced_mail_mitten: { id: "reinforced_mail_mitten", name: "Reinforced Mail Mittens" },
  reinforced_padded_mitten: { id: "reinforced_padded_mitten", name: "Reinforced Padded Mittens" },
  rough_tied_bracers: { id: "rough_tied_bracers", name: "Rough Tied Bracers", civilian: true  },
  roughtied_leather_bracers: { id: "roughtied_leather_bracers", name: "Roughtied Leather Bracers", civilian: true  },
  battania_warlord_bracers: { id: "battania_warlord_bracers", name: "Scale Warlord Bracers" },
  reinforced_leather_vambraces: { id: "reinforced_leather_vambraces", name: "Splint Vambraces" },
  strapped_leather_bracers: { id: "strapped_leather_bracers", name: "Strapped Leather Bracers", civilian: true  },
  studded_leather_vambraces: { id: "studded_leather_vambraces", name: "Studded Leather Vambraces" },
  studded_vambraces: { id: "studded_vambraces", name: "Studded Vambraces" },
  woven_leather_bracers: { id: "woven_leather_bracers", name: "Woven Leather Bracers" },
  eastern_wrapped_armguards: { id: "eastern_wrapped_armguards", name: "Wrapped Armguards", civilian: true  },
};

export const LEG_ARMORS: Record<string, Item> = {
  belted_leather_boots: { id: "belted_leather_boots", name: "Belted Leather Boots", civilian: true  },
  khuzait_curved_boots: { id: "khuzait_curved_boots", name: "Curved Boots", civilian: true  },
  decorated_imperial_boots: { id: "decorated_imperial_boots", name: "Decorated Plate Boots" },
  fine_town_boots: { id: "fine_town_boots", name: "Fine Town Boots", civilian: true  },
  turndown_leather_boots: { id: "turndown_leather_boots", name: "Folded Leather Boots", civilian: true  },
  folded_town_boots: { id: "folded_town_boots", name: "Folded Town Boots", civilian: true  },
  highland_boots: { id: "highland_boots", name: "Forester Boots", civilian: true  },
  battania_fur_boots: { id: "battania_fur_boots", name: "Fur Boots", civilian: true  },
  leather_boots: { id: "leather_boots", name: "Fur Rimmed Curved Boots", civilian: true  },
  battania_leather_boots: { id: "battania_leather_boots", name: "Highborns Leather Boots", civilian: true  },
  empire_horseman_boots: { id: "empire_horseman_boots", name: "Horsemans Boots", civilian: true  },
  northern_plated_boots: { id: "northern_plated_boots", name: "Huscarl Plated Boots" },
  ladys_shoe: { id: "ladys_shoe", name: "Ladies Shoes", civilian: true  },
  lamellar_plate_boots: { id: "lamellar_plate_boots", name: "Lamellar Plate Boots" },
  leather_cavalier_boots: { id: "leather_cavalier_boots", name: "Leather Cavalier Boots", civilian: true  },
  eastern_leather_boots: { id: "eastern_leather_boots", name: "Leather Riding Boots", civilian: true  },
  leather_shoes: { id: "leather_shoes", name: "Leather Shoes", civilian: true  },
  mail_cavalier_boots: { id: "mail_cavalier_boots", name: "Mail Cavalier Boots" },
  mail_chausses: { id: "mail_chausses", name: "Mail Chausses" },
  southern_moccasins: { id: "southern_moccasins", name: "Moccasins", civilian: true  },
  ragged_boots: { id: "ragged_boots", name: "Ragged Boots", civilian: true  },
  reinforced_suede_boots: { id: "reinforced_suede_boots", name: "Reinforced Suede Boots", civilian: true  },
  rough_tied_boots: { id: "rough_tied_boots", name: "Rough Tied Boots", civilian: true  },
  battania_warlord_boots: { id: "battania_warlord_boots", name: "Scaled Boots" },
  sturgia_boots_a: { id: "sturgia_boots_a", name: "Simple Leather Boots", civilian: true  },
  plated_strip_boots: { id: "plated_strip_boots", name: "Splint Boots" },
  strapped_leather_boots: { id: "strapped_leather_boots", name: "Strapped Leather Boots", civilian: true  },
  strapped_mail_chausses: { id: "strapped_mail_chausses", name: "Strapped Mail Chausses" },
  strapped_shoes: { id: "strapped_shoes", name: "Strapped Shoes", civilian: true  },
  steppe_leather_boots: { id: "steppe_leather_boots", name: "Sturdy Leather Boots", civilian: true  },
  sturgia_boots_c: { id: "sturgia_boots_c", name: "Tied Boots", civilian: true  },
  sturgia_boots_b: { id: "sturgia_boots_b", name: "Tied Leather Boots", civilian: true  },
  battania_woodland_boots: { id: "battania_woodland_boots", name: "Woodland Boots", civilian: true  },
  highland_leg_wrappings: { id: "highland_leg_wrappings", name: "Woodland Leg Wrappings", civilian: true  },
  woven_leather_boots: { id: "woven_leather_boots", name: "Woven Leather Boots", civilian: true  },
  sturgia_boots_d: { id: "sturgia_boots_d", name: "Wrapped Boots", civilian: true  },
  wrapped_leather_boots: { id: "wrapped_leather_boots", name: "Wrapped Leather Boots", civilian: true  },
  wrapped_shoes: { id: "wrapped_shoes", name: "Wrapped Shoes", civilian: true  },
};

export const MOUNTS: Record<string, Item> = {
  noble_horse_eastern: { id: "noble_horse_eastern", name: "Asaligat", civilian: true  },
  t2_aserai_horse: { id: "t2_aserai_horse", name: "Aserai Horse", civilian: true  },
  battania_horse: { id: "battania_horse", name: "Battanian Pony", civilian: true  },
  noble_horse_battania: { id: "noble_horse_battania", name: "Battanian Thoroughbred", civilian: true  },
  t2_battania_horse: { id: "t2_battania_horse", name: "Battanian Warmount", civilian: true  },
  camel: { id: "camel", name: "Camel", civilian: true  },
  charger: { id: "charger", name: "Charger", civilian: true  },
  noble_horse_imperial: { id: "noble_horse_imperial", name: "Cossian", civilian: true  },
  aserai_horse: { id: "aserai_horse", name: "Desert Horse", civilian: true  },
  desert_war_horse: { id: "desert_war_horse", name: "Desert War Horse", civilian: true  },
  noble_horse_western: { id: "noble_horse_western", name: "Destrier", civilian: true  },
  hunter: { id: "hunter", name: "Hunter", civilian: true  },
  special_camel: { id: "special_camel", name: "Husnphree", civilian: true  },
  t2_empire_horse: { id: "t2_empire_horse", name: "Imperial Charger", civilian: true  },
  noble_horse_khamseen: { id: "noble_horse_khamseen", name: "Khamseen", civilian: true  },
  empire_horse: { id: "empire_horse", name: "Midlands Palfrey", civilian: true  },
  mule: { id: "mule", name: "Mule", civilian: true  },
  noble_horse_southern: { id: "noble_horse_southern", name: "Nahasawi", civilian: true  },
  pack_camel: { id: "pack_camel", name: "Pack Camel", civilian: true  },
  noble_horse: { id: "noble_horse", name: "Pureblood", civilian: true  },
  vlandia_horse: { id: "vlandia_horse", name: "Saddle Horse", civilian: true  },
  steppe_war_horse: { id: "steppe_war_horse", name: "Steppe Charger", civilian: true  },
  khuzait_horse: { id: "khuzait_horse", name: "Steppe Horse", civilian: true  },
  t2_khuzait_horse: { id: "t2_khuzait_horse", name: "Steppe Warhorse", civilian: true  },
  storm_charger: { id: "storm_charger", name: "Storm Charger", civilian: true  },
  t2_sturgia_horse: { id: "t2_sturgia_horse", name: "Sturgian Chaser", civilian: true  },
  sturgia_horse: { id: "sturgia_horse", name: "Sturgian Trotter", civilian: true  },
  sumpter_horse: { id: "sumpter_horse", name: "Sumpter Horse", civilian: true  },
  noble_horse_northern: { id: "noble_horse_northern", name: "Tyal Horse", civilian: true  },
  t2_vlandia_horse: { id: "t2_vlandia_horse", name: "Vlandian Courser", civilian: true  },
  war_camel: { id: "war_camel", name: "War Camel", civilian: true  },
  war_horse: { id: "war_horse", name: "War Horse", civilian: true  },
  old_horse: { id: "old_horse", name: "Work Horse", civilian: true  },
};

export const MOUNT_HARNESSES: Record<string, Item> = {
  battania_horse_harness: { id: "battania_horse_harness", name: "Battania Horse Harness" },
  desert_cloth_harness: { id: "desert_cloth_harness", name: "Beduin Cloth Saddle" },
  aseran_village_harness: { id: "aseran_village_harness", name: "Beduin Common Saddle" },
  camel_saddle: { id: "camel_saddle", name: "Camel Saddle" },
  camel_saddle_a: { id: "camel_saddle_a", name: "Camel Saddle with Heavy Load" },
  camel_saddle_b: { id: "camel_saddle_b", name: "Camel Saddle with Light Load" },
  imperial_scale_barding: { id: "imperial_scale_barding", name: "Cataphract Scale Barding" },
  half_scale_barding: { id: "half_scale_barding", name: "Cataphracts Half Scale Barding" },
  celtic_frost: { id: "celtic_frost", name: "Celtic Frost" },
  chain_horse_harness: { id: "chain_horse_harness", name: "Chain Mail Horse Armor" },
  fortunas_choice: { id: "fortunas_choice", name: "Fortunas Choice" },
  halfchain_barding: { id: "halfchain_barding", name: "Half Mail Barding" },
  battania_horse_harness_halfscaled: { id: "battania_horse_harness_halfscaled", name: "Half Scaled Barding" },
  imperial_riding_harness: { id: "imperial_riding_harness", name: "Imperial Riding Harness" },
  steppe_half_barding: { id: "steppe_half_barding", name: "Lamellar Half Barding" },
  light_harness: { id: "light_harness", name: "Light Harness" },
  northern_light_harness: { id: "northern_light_harness", name: "Light Saddle" },
  mule_load_c: { id: "mule_load_c", name: "Mule Harness with Bags" },
  mule_load_b: { id: "mule_load_b", name: "Mule Harness with Baskets" },
  mule_load_a: { id: "mule_load_a", name: "Mule Harness with Pack" },
  chain_barding: { id: "chain_barding", name: "Reinforced Chainmail Barding" },
  half_mail_and_plate_barding: { id: "half_mail_and_plate_barding", name: "Reinforced Half Plate Barding" },
  studded_steppe_barding: { id: "studded_steppe_barding", name: "Reinforced Mail Barding" },
  mail_and_plate_barding: { id: "mail_and_plate_barding", name: "Reinforced Plate Barding" },
  northern_ring_barding: { id: "northern_ring_barding", name: "Ring Mail Barding" },
  northern_noble_harness: { id: "northern_noble_harness", name: "Rough Cavalry Saddle" },
  bandit_saddle_desert: { id: "bandit_saddle_desert", name: "Rugged Beduin Saddle" },
  bandit_saddle_highland: { id: "bandit_saddle_highland", name: "Rugged Fur Saddle" },
  bandit_saddle_steppe: { id: "bandit_saddle_steppe", name: "Rugged Saddle" },
  saddle_of_aeneas: { id: "saddle_of_aeneas", name: "Saddle of Aeneas" },
  battania_horse_harness_scaled: { id: "battania_horse_harness_scaled", name: "Scale Barding" },
  steppe_fur_harness: { id: "steppe_fur_harness", name: "Steppe Fur Harness" },
  steppe_harness: { id: "steppe_harness", name: "Steppe Saddle" },
  stripped_leather_harness: { id: "stripped_leather_harness", name: "Striped Leather Harness" },
};

export const WEAPONS: Record<string, Item> = {
  adarga: { id: "adarga", name: "Adarga" },
  crossbow_c: { id: "crossbow_c", name: "Arbalest" },
  vlandia_noble_sword_2_t5: { id: "vlandia_noble_sword_2_t5", name: "Arming Sword with Circle" },
  default_arrows: { id: "default_arrows", name: "Arrows" },
  avalanche_2haxe: { id: "avalanche_2haxe", name: "Avalanche" },
  sturgia_sword_2_t3: { id: "sturgia_sword_2_t3", name: "Backsword" },
  ballista_projectile: { id: "ballista_projectile", name: "Ballista Arrows" },
  ballista_projectile_burning: { id: "ballista_projectile_burning", name: "Ballista Arrows" },
  bamboo_axe_t4: { id: "bamboo_axe_t4", name: "Bamboo Axe" },
  aserai_axe_2_t2: { id: "aserai_axe_2_t2", name: "Bamboo Handled Ascia Axe" },
  southern_small_axe_t2: { id: "southern_small_axe_t2", name: "Bamboo Handled Axe" },
  barbed_arrows: { id: "barbed_arrows", name: "Barbed Arrows" },
  battania_2hsword_5_t5: { id: "battania_2hsword_5_t5", name: "Battanian Mountain Blade" },
  battered_horsemans_kite_shield: { id: "battered_horsemans_kite_shield", name: "Battered Horseman's Kite Shield" },
  battered_kite_shield: { id: "battered_kite_shield", name: "Battered Kite Shield" },
  battle_axe_t4: { id: "battle_axe_t4", name: "Battle Axe" },
  bearded_axe_t3: { id: "bearded_axe_t3", name: "Bearded Axe" },
  billhook_polearm_t2: { id: "billhook_polearm_t2", name: "Billhook" },
  black_heart_2haxe_t3: { id: "black_heart_2haxe_t3", name: "Black Heart" },
  peasant_hammer_1_t1: { id: "peasant_hammer_1_t1", name: "Blacksmith Hammer" },
  blunt_arrows: { id: "blunt_arrows", name: "Blunt Arrows" },
  bo_staff: { id: "bo_staff", name: "Bo staff" },
  bodkin_arrows_b: { id: "bodkin_arrows_b", name: "Bodkin Arrows" },
  bolt_a: { id: "bolt_a", name: "Bolt" },
  bone_crusher_mace_t3: { id: "bone_crusher_mace_t3", name: "Bone Crusher" },
  boulder: { id: "boulder", name: "Boulder" },
  crossbow_f: { id: "crossbow_f", name: "Bound Crossbow" },
  bracketed_heater_shield: { id: "bracketed_heater_shield", name: "Bracketed Heater Shield" },
  broad_arming_sword_t4: { id: "broad_arming_sword_t4", name: "Broad Arming Sword" },
  northern_javelin_3_t4: { id: "northern_javelin_3_t4", name: "Broad Blade Javelin" },
  empire_throwingknife_t5: { id: "empire_throwingknife_t5", name: "Broad Bladed Throwing Knives" },
  broad_falchion_sword_t3: { id: "broad_falchion_sword_t3", name: "Broad Falchion" },
  broad_ild_sword_t3: { id: "broad_ild_sword_t3", name: "Broad Ild" },
  southern_broad_2hsword_t4: { id: "southern_broad_2hsword_t4", name: "Broad Kaskara" },
  northern_spear_2_t3: { id: "northern_spear_2_t3", name: "Broad Leaf Shaped Spear" },
  battania_sword_2_t3: { id: "battania_sword_2_t3", name: "Broad Ridged Shortsword" },
  western_2hsword_t4: { id: "western_2hsword_t4", name: "Broad Two Hander" },
  tzkurion_axe_t3: { id: "tzkurion_axe_t3", name: "Broad Tzkurion" },
  battania_sword_3_t3: { id: "battania_sword_3_t3", name: "Broadsword" },
  battania_large_shield_a: { id: "battania_large_shield_a", name: "Bronze Reinforced Highland Large Shield" },
  empire_mace_3_t4: { id: "empire_mace_3_t4", name: "Calradic Mace" },
  empire_lance_3_t5: { id: "empire_lance_3_t5", name: "Cataphract Lance" },
  empire_mace_5_t5: { id: "empire_mace_5_t5", name: "Cataphract Mace" },
  bound_horsemans_kite_shield: { id: "bound_horsemans_kite_shield", name: "Cavalry Kite Shield" },
  northern_scouts_shield: { id: "northern_scouts_shield", name: "Cavalry Kite Shield" },
  cleaver_sword_t3: { id: "cleaver_sword_t3", name: "Cleaver" },
  sturgia_axe_3_t3: { id: "sturgia_axe_3_t3", name: "Commoner Axe" },
  empire_lance_2_t4: { id: "empire_lance_2_t4", name: "Courser Lance" },
  vlandia_noble_sword_4_t5: { id: "vlandia_noble_sword_4_t5", name: "Crescent Guarded Arming Sword" },
  crossbow_e: { id: "crossbow_e", name: "Crossbow" },
  sturgia_old_shield_b: { id: "sturgia_old_shield_b", name: "Crude Large Round Shield" },
  curved_round_shield: { id: "curved_round_shield", name: "Curved Round Shield" },
  dawnbreaker_sword_t3: { id: "dawnbreaker_sword_t3", name: "Dawnbreaker" },
  vlandia_noble_sword_1_t5: { id: "vlandia_noble_sword_1_t5", name: "Decorated Arming Sword" },
  battania_noble_sword_3_t5: { id: "battania_noble_sword_3_t5", name: "Decorated Broadsword" },
  noyans_shield: { id: "noyans_shield", name: "Decorated Eastern Shield" },
  sturgia_noble_sword_3_t5: { id: "sturgia_noble_sword_3_t5", name: "Decorated Fullered Sword" },
  aserai_noble_sword_1_t5: { id: "aserai_noble_sword_1_t5", name: "Decorated Kaskara" },
  aserai_noble_sword_2_t5: { id: "aserai_noble_sword_2_t5", name: "Decorated Long Scimitar" },
  sturgia_noble_sword_2_t5: { id: "sturgia_noble_sword_2_t5", name: "Decorated Long Warsword" },
  emirs_oval_shield: { id: "emirs_oval_shield", name: "Decorated Oval Shield" },
  highland_scouts_shield: { id: "highland_scouts_shield", name: "Decorated Round Shield" },
  khuzait_noble_sword_1_t5: { id: "khuzait_noble_sword_1_t5", name: "Decorated Saber" },
  aserai_noble_sword_3_t5: { id: "aserai_noble_sword_3_t5", name: "Decorated Scimitar with Wide Grip" },
  empire_noble_sword_1_t5: { id: "empire_noble_sword_1_t5", name: "Decorated Short Spatha" },
  desert_long_sword_t4: { id: "desert_long_sword_t4", name: "Desert Long Sword" },
  desert_oval_shield: { id: "desert_oval_shield", name: "Desert Oval Shield" },
  bound_desert_round_shield: { id: "bound_desert_round_shield", name: "Desert Round Shield" },
  bound_desert_round_sparring_shield: { id: "bound_desert_round_sparring_shield", name: "Desert Round Sparring Shield" },
  sturgia_2haxe_1_t4: { id: "sturgia_2haxe_1_t4", name: "Drilled Two Handed Axe" },
  sturgia_lance_1_t4: { id: "sturgia_lance_1_t4", name: "Druzhinnik Lance" },
  early_retirement_2hsword_t3: { id: "early_retirement_2hsword_t3", name: "Early Retirement" },
  steppe_guardian_shield: { id: "steppe_guardian_shield", name: "Eastern Cavalry Shield" },
  khuzait_mace_2_t4: { id: "khuzait_mace_2_t4", name: "Eastern Heavy Mace" },
  aserai_noble_sword_4_t5: { id: "aserai_noble_sword_4_t5", name: "Engraved Angular Kaskara" },
  battania_noble_sword_1_t5: { id: "battania_noble_sword_1_t5", name: "Engraved Backsword" },
  execution_axe: { id: "execution_axe", name: "Execution Axe" },
  aserai_2haxe_2_t4: { id: "aserai_2haxe_2_t4", name: "Executioner Axe" },
  falchion_sword_t2: { id: "falchion_sword_t2", name: "Falchion" },
  battania_2hsword_4_t4: { id: "battania_2hsword_4_t4", name: "Falx" },
  hooked_cleaver: { id: "hooked_cleaver", name: "Falx Knife" },
  crossbow_g: { id: "crossbow_g", name: "Fine Crossbow" },
  fine_pike_t4: { id: "fine_pike_t4", name: "Fine Pike" },
  battania_sword_4_t4: { id: "battania_sword_4_t4", name: "Fine Steel Cavalry Broadsword" },
  northern_spear_4_t5: { id: "northern_spear_4_t5", name: "Fine Steel Hewing Spear" },
  eastern_spear_4_t4: { id: "eastern_spear_4_t4", name: "Fine Steel Leaf Spear" },
  aserai_sword_4_t4: { id: "aserai_sword_4_t4", name: "Fine Steel Long Kaskara" },
  khuzait_mace_3_t4: { id: "khuzait_mace_3_t4", name: "Fine Steel Mace" },
  empire_polearm_2_t5: { id: "empire_polearm_2_t5", name: "Fine Steel Menavlion" },
  empire_sword_5_t4: { id: "empire_sword_5_t4", name: "Fine Steel Paramerion" },
  khuzait_sword_4_t4: { id: "khuzait_sword_4_t4", name: "Fine Steel Saber" },
  empire_sword_4_t4: { id: "empire_sword_4_t4", name: "Fine Steel Spatha" },
  northern_2hsword_t4: { id: "northern_2hsword_t4", name: "Fine Steel Two Handed Sword" },
  pot: { id: "pot", name: "Fire Pot" },
  northern_javelin_1_t2: { id: "northern_javelin_1_t2", name: "Fish Harpoon" },
  flat_heater_shield: { id: "flat_heater_shield", name: "Flat Heater Shield" },
  fortified_kite_shield: { id: "fortified_kite_shield", name: "Fortified Kite Shield" },
  western_throwing_axe_1_t1: { id: "western_throwing_axe_1_t1", name: "Franceska" },
  vlandia_mace_2_t4: { id: "vlandia_mace_2_t4", name: "Fullered Cavalry Mace" },
  aserai_mace_2_t2: { id: "aserai_mace_2_t2", name: "Fullered Light Mace" },
  sturgia_sword_5_t5: { id: "sturgia_sword_5_t5", name: "Fullered Long Warsword" },
  sturgia_sword_5_t4: { id: "sturgia_sword_5_t4", name: "Fullered Narrow Warsword" },
  sturgia_axe_2_t2: { id: "sturgia_axe_2_t2", name: "Gallogaich Axe" },
  khuzait_polearm_1_t4: { id: "khuzait_polearm_1_t4", name: "Glaive" },
  sturgia_noble_sword_4_t5: { id: "sturgia_noble_sword_4_t5", name: "Gold Bound Short Warsword" },
  vlandia_noble_sword_3_t5: { id: "vlandia_noble_sword_3_t5", name: "Gold Engraved Arming Sword" },
  grapeshot_projectile: { id: "grapeshot_projectile", name: "Grapeshot Ammo" },
  grapeshot_fire_projectile: { id: "grapeshot_fire_projectile", name: "Grapeshot Ammo" },
  grapeshot_stack: { id: "grapeshot_stack", name: "Grapeshot Stack" },
  grapeshot_fire_stack: { id: "grapeshot_fire_stack", name: "Grapeshot Stack" },
  generic_javelin_1_t3: { id: "generic_javelin_1_t3", name: "Harpoon" },
  peasant_hatchet_1_t1: { id: "peasant_hatchet_1_t1", name: "Hatchet" },
  heater_shield_with_cutout: { id: "heater_shield_with_cutout", name: "Heater Shield with Cutout" },
  bolt_b: { id: "bolt_b", name: "Heavy Bolt" },
  khuzait_lance_2_t4: { id: "khuzait_lance_2_t4", name: "Heavy Cavalry Lance" },
  crossbow_b: { id: "crossbow_b", name: "Heavy Crossbow" },
  sturgia_lance_2_t5: { id: "sturgia_lance_2_t5", name: "Heavy Druzhinnik Lance" },
  aserai_2haxe_3_t5: { id: "aserai_2haxe_3_t5", name: "Heavy Executioner Axe" },
  khuzait_mace_4_t5: { id: "khuzait_mace_4_t5", name: "Heavy Flanged Mace" },
  heavy_heater_shield: { id: "heavy_heater_shield", name: "Heavy Heater Shield" },
  aserai_mace_3_t3: { id: "aserai_mace_3_t3", name: "Heavy Horsemans Mace" },
  vlandia_lance_3_t5: { id: "vlandia_lance_3_t5", name: "Heavy Knight Lance" },
  bolt_d: { id: "bolt_d", name: "Heavy Quarrel" },
  steppe_heavy_bow: { id: "steppe_heavy_bow", name: "Heavy Recurve Bow" },
  heavy_round_shield: { id: "heavy_round_shield", name: "Heavy Round Shield" },
  khuzait_sword_5_t4: { id: "khuzait_sword_5_t4", name: "Heavy Saber" },
  crossbow_d: { id: "crossbow_d", name: "Hickory Crossbow" },
  battania_sword_5_t5: { id: "battania_sword_5_t5", name: "Highland Broad Blade" },
  battania_2hsword_2_t3: { id: "battania_2hsword_2_t3", name: "Highland Broadsword" },
  celtic_dagger: { id: "celtic_dagger", name: "Highland Dagger" },
  battania_noble_sword_2_t5: { id: "battania_noble_sword_2_t5", name: "Highland Fine Steel Blade" },
  battania_2hsword_5_t4: { id: "battania_2hsword_5_t4", name: "Highland Fine Two Handed Sword" },
  battania_large_shield_c: { id: "battania_large_shield_c", name: "Highland Large Shield" },
  highland_riders_shield: { id: "highland_riders_shield", name: "Highland Round Shield" },
  battania_mace_2_t2: { id: "battania_mace_2_t2", name: "Highland Spiked Club" },
  highland_throwing_axe_1_t2: { id: "highland_throwing_axe_1_t2", name: "Highland Throwing Axe" },
  woodland_throwing_axe_1_t1: { id: "woodland_throwing_axe_1_t1", name: "Highland Throwing Axe" },
  celtic_throwing_dagger: { id: "celtic_throwing_dagger", name: "Highland Throwing Dagger" },
  highland_spear_t2: { id: "highland_spear_t2", name: "Highland War Spear" },
  peasant_2haxe_1_t1: { id: "peasant_2haxe_1_t1", name: "Hoe" },
  hooked_axe_t4: { id: "hooked_axe_t4", name: "Hooked Cavalry Axe" },
  western_javelin_3_t4: { id: "western_javelin_3_t4", name: "Hooked Javelin" },
  horse_whip: { id: "horse_whip", name: "Horse Whip" },
  eastern_javelin_2_t3: { id: "eastern_javelin_2_t3", name: "Horseman Javelin" },
  hunting_bow: { id: "hunting_bow", name: "Hunting Bow" },
  arrow_emp_1_a: { id: "arrow_emp_1_a", name: "Imperial Arrows" },
  empire_mace_2_t4: { id: "empire_mace_2_t4", name: "Imperial Light Mace" },
  vlandia_axe_1_t3: { id: "vlandia_axe_1_t3", name: "Infantry Axe" },
  vlandia_sword_1_t2: { id: "vlandia_sword_1_t2", name: "Iron Arming Sword" },
  battania_2hsword_1_t2: { id: "battania_2hsword_1_t2", name: "Iron Broadsword" },
  aserai_sword_1_t2: { id: "aserai_sword_1_t2", name: "Iron Flyssa" },
  peasant_pitchfork_1_t1: { id: "peasant_pitchfork_1_t1", name: "Iron Pitchfork" },
  battania_large_shield_b: { id: "battania_large_shield_b", name: "Iron Reinforced Highland Large Shield" },
  ironrim_kite_shield: { id: "ironrim_kite_shield", name: "Iron Rimmed Kite Shield" },
  sturgia_old_shield_a: { id: "sturgia_old_shield_a", name: "Iron Rimmed Large Round Shield" },
  studded_round_shield: { id: "studded_round_shield", name: "Iron Round Shield" },
  khuzait_sword_1_t2: { id: "khuzait_sword_1_t2", name: "Iron Saber" },
  aserai_sword_2_t2: { id: "aserai_sword_2_t2", name: "Iron Scimitar" },
  empire_sword_1_t2: { id: "empire_sword_1_t2", name: "Iron Spatha" },
  iron_spatha_sword_t2: { id: "iron_spatha_sword_t2", name: "Iron Spatha" },
  northern_spear_3_t4: { id: "northern_spear_3_t4", name: "Jagged Fine Steel Spear" },
  eastern_javelin_1_t2: { id: "eastern_javelin_1_t2", name: "Jagged Javelin" },
  eastern_spear_1_t2: { id: "eastern_spear_1_t2", name: "Jagged Spear" },
  eastern_throwing_spear_1_t3: { id: "eastern_throwing_spear_1_t3", name: "Jagged Throwing Spear" },
  eastern_javelin_3_t4: { id: "eastern_javelin_3_t4", name: "Jereed" },
  judgement_mace_t3: { id: "judgement_mace_t3", name: "Judgement" },
  justicier_2hsword: { id: "justicier_2hsword", name: "Justicier" },
  western_kite_shield: { id: "western_kite_shield", name: "Kite Shield" },
  western_kite_sparring_shield: { id: "western_kite_sparring_shield", name: "Kite Sparring Shield" },
  vlandia_lance_2_t4: { id: "vlandia_lance_2_t4", name: "Knight Lance" },
  knights_fall_mace_t3: { id: "knights_fall_mace_t3", name: "Knight's Fall" },
  vlandia_sword_3_t4: { id: "vlandia_sword_3_t4", name: "Knightly Arming Sword" },
  chivalric_kite_shield: { id: "chivalric_kite_shield", name: "Knights Kite Shield" },
  jousting_shield: { id: "jousting_shield", name: "Knights Shield" },
  southern_spear_3_t3: { id: "southern_spear_3_t3", name: "Knob Headed Spear" },
  battania_mace_1_t2: { id: "battania_mace_1_t2", name: "Knobbed Club" },
  large_adarga: { id: "large_adarga", name: "Large Adarga" },
  large_franziskaa_axe_t3: { id: "large_franziskaa_axe_t3", name: "Large Franziska Axe" },
  leather_round_shield: { id: "leather_round_shield", name: "Large Round Shield" },
  leafblade_throwing_knife: { id: "leafblade_throwing_knife", name: "Leafblade Throwing Knife" },
  leather_bound_kite_shield: { id: "leather_bound_kite_shield", name: "Leather Bound Kite Shield" },
  bodkin_arrows_c: { id: "bodkin_arrows_c", name: "Light Bodkin Arrows" },
  bolt_c: { id: "bolt_c", name: "Light Bolt" },
  light_horsemans_kite_shield: { id: "light_horsemans_kite_shield", name: "Light Cavalry Kite Shield" },
  empire_lance_1_t3: { id: "empire_lance_1_t3", name: "Light Cavalry Lance" },
  crossbow_a: { id: "crossbow_a", name: "Light Crossbow" },
  vlandia_lance_1_t3: { id: "vlandia_lance_1_t3", name: "Light Lance" },
  light_mace_t3: { id: "light_mace_t3", name: "Light Mace" },
  bolt_e: { id: "bolt_e", name: "Light Quarrel" },
  empire_mace_4_t5: { id: "empire_mace_4_t5", name: "Light Royal Mace" },
  shishpar_mace_t4: { id: "shishpar_mace_t4", name: "Light Shishpar Mace" },
  khuzait_lance_1_t3: { id: "khuzait_lance_1_t3", name: "Light Steppe Rider Lance" },
  khuzait_noble_sword_2_t5: { id: "khuzait_noble_sword_2_t5", name: "Lion Imprinted Saber" },
  aserai_sword_5_t4: { id: "aserai_sword_5_t4", name: "Long Fine Steel Scimitar" },
  western_spear_4_t4: { id: "western_spear_4_t4", name: "Long Fine Steel Spear" },
  khuzait_polearm_2_t5: { id: "khuzait_polearm_2_t5", name: "Long Glaive" },
  western_spear_3_t3: { id: "western_spear_3_t3", name: "Long Infantry Spear" },
  khuzait_sword_3_t3: { id: "khuzait_sword_3_t3", name: "Long Saber" },
  southern_spear_3_t4: { id: "southern_spear_3_t4", name: "Long Thamaskene Tipped Spear" },
  sturgia_sword_4_t4: { id: "sturgia_sword_4_t4", name: "Long Warsword" },
  glen_ranger_bow: { id: "glen_ranger_bow", name: "Longbow" },
  vlandic_arrows: { id: "vlandic_arrows", name: "Lowland Arrows" },
  western_javelin_2_t3: { id: "western_javelin_2_t3", name: "Lowland Javelin" },
  lowland_longbow: { id: "lowland_longbow", name: "Lowland Longbow" },
  lowland_throwing_knife: { id: "lowland_throwing_knife", name: "Lowland Throwing Knife" },
  worn_horsemans_kite_shield: { id: "worn_horsemans_kite_shield", name: "Makeshift Horsemans Kite Shield" },
  old_kite_shield: { id: "old_kite_shield", name: "Makeshift Kite Shield" },
  old_kite_sparring_shield: { id: "old_kite_sparring_shield", name: "Makeshift Kite Sparring Shield" },
  peasant_maul_t1: { id: "peasant_maul_t1", name: "Makeshift Sledgehammer" },
  aserai_lance_1_t5: { id: "aserai_lance_1_t5", name: "Mamluke Lance" },
  empire_polearm_1_t4: { id: "empire_polearm_1_t4", name: "Menavlion" },
  military_fork_t2: { id: "military_fork_t2", name: "Military Fork" },
  aserai_mace_1_t2: { id: "aserai_mace_1_t2", name: "Militia Mace" },
  pernach_mace_t3: { id: "pernach_mace_t3", name: "Militia Pernach" },
  morningstar_mace_t3: { id: "morningstar_mace_t3", name: "Morningstar" },
  mountain_hunting_bow: { id: "mountain_hunting_bow", name: "Mountain Hunting Bow" },
  aserai_sword_6_t4: { id: "aserai_sword_6_t4", name: "Narrow Fine Steel Kaskara" },
  eastern_spear_2_t3: { id: "eastern_spear_2_t3", name: "Narrow Long Headed Spear" },
  narrow_sword_t3: { id: "narrow_sword_t3", name: "Narrow Sword" },
  noble_bow: { id: "noble_bow", name: "Noble Bow" },
  khuzait_lance_3_t5: { id: "khuzait_lance_3_t5", name: "Noble Cavalry Lance" },
  noble_long_bow: { id: "noble_long_bow", name: "Noble Long Bow" },
  nomad_bow: { id: "nomad_bow", name: "Nomad Bow" },
  nordic_shortbow: { id: "nordic_shortbow", name: "Nordic Shortbow" },
  battania_axe_1_t2: { id: "battania_axe_1_t2", name: "Norse Hatchet" },
  viking_round_shield: { id: "viking_round_shield", name: "Norse Round Shield" },
  northern_axe_t3: { id: "northern_axe_t3", name: "Northlander Broad Axe" },
  sturgia_2haxe_2_t5: { id: "sturgia_2haxe_2_t5", name: "Northlander Decorated Two Handed Axe" },
  battania_2hsword_3_t3: { id: "battania_2hsword_3_t3", name: "Northlander Wide Fullered Greatsword" },
  military_fork_pike_t3: { id: "military_fork_pike_t3", name: "Notched Military Fork" },
  battania_axe_2_t4: { id: "battania_axe_2_t4", name: "One Handed Bearded Axe" },
  ornate_adarga: { id: "ornate_adarga", name: "Ornate Adarga" },
  pavise_shield: { id: "pavise_shield", name: "Pavise Shield" },
  vlandia_mace_3_t5: { id: "vlandia_mace_3_t5", name: "Pernach" },
  peasant_pickaxe_1_t1: { id: "peasant_pickaxe_1_t1", name: "Pickaxe" },
  piercing_arrows: { id: "piercing_arrows", name: "Piercing Arrows" },
  vlandia_pike_1_t5: { id: "vlandia_pike_1_t5", name: "Pike" },
  imperial_throwing_spear_1_t4: { id: "imperial_throwing_spear_1_t4", name: "Pilum" },
  peasant_pitchfork_2_t1: { id: "peasant_pitchfork_2_t1", name: "Pitchfork" },
  pointed_falchion_sword_t4: { id: "pointed_falchion_sword_t4", name: "Pointed Falchion" },
  sturgia_sword_3_t3: { id: "sturgia_sword_3_t3", name: "Pointy Warsword" },
  easter_polesword_t4: { id: "easter_polesword_t4", name: "Polesword" },
  training_bow: { id: "training_bow", name: "Practice Bow" },
  training_longbow: { id: "training_longbow", name: "Practice Longbow" },
  practice_spear_t1: { id: "practice_spear_t1", name: "Practice Spear" },
  pugio: { id: "pugio", name: "Pugio" },
  push_fork: { id: "push_fork", name: "Push Fork" },
  northern_throwing_axe_1_t1: { id: "northern_throwing_axe_1_t1", name: "Raider Throwing Axe" },
  range_arrows: { id: "range_arrows", name: "Range Arrows" },
  highland_ranger_bow: { id: "highland_ranger_bow", name: "Ranger Bow" },
  reaper_falx: { id: "reaper_falx", name: "Reaper" },
  sturgia_axe_5_t5: { id: "sturgia_axe_5_t5", name: "Rectangular Bitted Axe" },
  heavy_horsemans_kite_shield: { id: "heavy_horsemans_kite_shield", name: "Reinforced Cavalry Kite Shield" },
  northern_horsemans_shield: { id: "northern_horsemans_shield", name: "Reinforced Cavalry Shield" },
  reinforced_horsemans_kite_shield: { id: "reinforced_horsemans_kite_shield", name: "Reinforced Cavalry Small Shield" },
  desert_round_shield: { id: "desert_round_shield", name: "Reinforced Desert Round Shield" },
  reinforced_flat_kite_shield: { id: "reinforced_flat_kite_shield", name: "Reinforced Flat Kite Shield" },
  highland_spear_3_t3: { id: "highland_spear_3_t3", name: "Reinforced Highland Spear" },
  ironrim_riders_kite_shield: { id: "ironrim_riders_kite_shield", name: "Reinforced Iron Rimmed Kite Shield" },
  reinforced_kite_shield: { id: "reinforced_kite_shield", name: "Reinforced Kite Shield" },
  strapped_round_shield: { id: "strapped_round_shield", name: "Reinforced Large Round Shield" },
  sturgia_old_shield_c: { id: "sturgia_old_shield_c", name: "Reinforced Large Round Shield" },
  stronger_reinforced_kite_shield: { id: "stronger_reinforced_kite_shield", name: "Reinforced Oaken Kite Shield" },
  southern_oval_shield: { id: "southern_oval_shield", name: "Reinforced Oval Shield" },
  battania_shield_targe_a: { id: "battania_shield_targe_a", name: "Reinforced Targe" },
  stronger_footmans_wicker_shield: { id: "stronger_footmans_wicker_shield", name: "Reinforced Wicker Shield" },
  stronger_eastern_wicker_shield: { id: "stronger_eastern_wicker_shield", name: "Reinforced Wicker Square Shield" },
  battania_polearm_1_t5: { id: "battania_polearm_1_t5", name: "Rhomphalia" },
  western_riders_kite_shield: { id: "western_riders_kite_shield", name: "Rider's Kite Shield" },
  western_riders_kite_sparring_shield: { id: "western_riders_kite_sparring_shield", name: "Riders Sparring Kite Shield" },
  vlandia_sword_4_t4: { id: "vlandia_sword_4_t4", name: "Ridged Arming Sword" },
  ridged_2hsword_t4: { id: "ridged_2hsword_t4", name: "Ridged Great Saber" },
  battania_sword_1_t2: { id: "battania_sword_1_t2", name: "Ridged Iron Broadsword" },
  kaskara_2hsword_t3: { id: "kaskara_2hsword_t3", name: "Ridged Long Kaskara" },
  ridged_sabre_sword_t4: { id: "ridged_sabre_sword_t4", name: "Ridged Saber" },
  vlandia_sword_2_t3: { id: "vlandia_sword_2_t3", name: "Ridged Tipped Arming Sword" },
  battania_axe_3_t5: { id: "battania_axe_3_t5", name: "Round Bitted Fine Steel Hatchet" },
  northern_round_shield: { id: "northern_round_shield", name: "Round Shield" },
  decorated_steppe_shield: { id: "decorated_steppe_shield", name: "Round Steppe Shield" },
  peasant_polearm_1_t1: { id: "peasant_polearm_1_t1", name: "Scythe" },
  seax: { id: "seax", name: "Seax" },
  sentinel_2hsword: { id: "sentinel_2hsword", name: "Sentinel" },
  vlandia_2haxe_1_t4: { id: "vlandia_2haxe_1_t4", name: "Short Bill" },
  aserai_2haxe_1_t3: { id: "aserai_2haxe_1_t3", name: "Short Handled Bardiche" },
  imperial_spear_t2: { id: "imperial_spear_t2", name: "Short Militia Spear" },
  northern_spear_1_t2: { id: "northern_spear_1_t2", name: "Short Simple Raider Spear" },
  short_sword_t3: { id: "short_sword_t3", name: "Short Sword" },
  peasant_sickle_1_t1: { id: "peasant_sickle_1_t1", name: "Sickle" },
  bastard_sword_t2: { id: "bastard_sword_t2", name: "Simple Bastard Sword" },
  western_spear_1_t2: { id: "western_spear_1_t2", name: "Simple Commoner Spear" },
  western_javelin_1_t2: { id: "western_javelin_1_t2", name: "Simple Javelin" },
  simple_pike_t2: { id: "simple_pike_t2", name: "Simple Pike" },
  northern_battle_axe_t3: { id: "northern_battle_axe_t3", name: "Simple Raider Battle Axe" },
  simple_sabre_sword_t2: { id: "simple_sabre_sword_t2", name: "Simple Saber" },
  simple_back_sword_t2: { id: "simple_back_sword_t2", name: "Simple Scimitar" },
  composite_bow: { id: "composite_bow", name: "Simple Short Bow" },
  western_spear_2_t2: { id: "western_spear_2_t2", name: "Simple Short Spear" },
  simple_sparth_axe_t2: { id: "simple_sparth_axe_t2", name: "Simple Sparth Axe" },
  peasant_maul_t1_2: { id: "peasant_maul_t1_2", name: "Sledgehammer" },
  aserai_sword_3_t3: { id: "aserai_sword_3_t3", name: "Slightly Ridged Flyssa" },
  small_bit_axe_t2: { id: "small_bit_axe_t2", name: "Small Bit Axe" },
  horsemans_heater_shield: { id: "horsemans_heater_shield", name: "Small Cavalry Heater Shield" },
  small_flat_heater_shield: { id: "small_flat_heater_shield", name: "Small Flat Heater Shield" },
  small_heater_shield: { id: "small_heater_shield", name: "Small Heater Shield" },
  small_spurred_axe_t2: { id: "small_spurred_axe_t2", name: "Small Spurred Axe" },
  northern_round_sparring_shield: { id: "northern_round_sparring_shield", name: "Sparring Round Shield" },
  battania_targe_b_sparring: { id: "battania_targe_b_sparring", name: "Sparring Targe" },
  empire_sword_3_t3: { id: "empire_sword_3_t3", name: "Spatha" },
  empire_noble_sword_3_t5: { id: "empire_noble_sword_3_t5", name: "Spatha Blade with Ring Pommel" },
  empire_sword_2_t3: { id: "empire_sword_2_t3", name: "Spatha With Narrow Fuller" },
  vlandia_axe_2_t4: { id: "vlandia_axe_2_t4", name: "Spiked Battle Axe" },
  empire_mace_1_t2: { id: "empire_mace_1_t2", name: "Spiked Club" },
  vlandia_mace_1_t2: { id: "vlandia_mace_1_t2", name: "Spiked Mace" },
  aserai_mace_4_t4: { id: "aserai_mace_4_t4", name: "Spiralled Mace" },
  battania_2haxe_1_t2: { id: "battania_2haxe_1_t2", name: "Square Bit Two Handed Axe" },
  bodkin_arrows_a: { id: "bodkin_arrows_a", name: "Stacked Bodkin Arrows" },
  heavy_steppe_arrows: { id: "heavy_steppe_arrows", name: "Stacked Steppe Arrows" },
  star_falchion_sword_t3: { id: "star_falchion_sword_t3", name: "Star Falchion" },
  eastern_steel_mace_t4: { id: "eastern_steel_mace_t4", name: "Steel Mace" },
  steel_round_shield: { id: "steel_round_shield", name: "Steel Round Shield" },
  steel_mace_t3: { id: "steel_mace_t3", name: "Steel Shestopyor" },
  highland_spear_4_t4: { id: "highland_spear_4_t4", name: "Steel Tipped Hooked Spear" },
  steppe_arrows: { id: "steppe_arrows", name: "Steppe Arrows" },
  steppe_bow: { id: "steppe_bow", name: "Steppe Bow" },
  khuzait_mace_1_t2: { id: "khuzait_mace_1_t2", name: "Steppe Light Mace" },
  composite_steppe_bow: { id: "composite_steppe_bow", name: "Steppe Recurve Bow" },
  steppe_war_bow: { id: "steppe_war_bow", name: "Steppe War Bow" },
  throwing_stone: { id: "throwing_stone", name: "Stone" },
  khuzait_sword_2_t3: { id: "khuzait_sword_2_t3", name: "Straight Saber" },
  longbow_recurve_desert_bow: { id: "longbow_recurve_desert_bow", name: "Strong Tribesman Bow" },
  studded_adarga: { id: "studded_adarga", name: "Studded Adarga" },
  studded_bound_kite_shield: { id: "studded_bound_kite_shield", name: "Studded Bound Kite Shield" },
  khuzait_noble_sword_3_t5: { id: "khuzait_noble_sword_3_t5", name: "Tall Gripped Ild Sword" },
  tall_heater_shield: { id: "tall_heater_shield", name: "Tall Heater Shield" },
  sturgia_sword_1_t2: { id: "sturgia_sword_1_t2", name: "Tapered Blade" },
  western_2hsword_t3: { id: "western_2hsword_t3", name: "Tapered Two-Hander" },
  battania_targe_b: { id: "battania_targe_b", name: "Targe" },
  thamaskene_pike_t4: { id: "thamaskene_pike_t4", name: "Thamaskene Pike" },
  aserai_sword_7_t5: { id: "aserai_sword_7_t5", name: "Thamaskene Steel Kaskara" },
  empire_noble_sword_2_t5: { id: "empire_noble_sword_2_t5", name: "Thamaskene Steel Spatha" },
  empire_sword_6_t5: { id: "empire_sword_6_t5", name: "Thamaskene Steel Spathion" },
  vlandia_2hsword_2_t5: { id: "vlandia_2hsword_2_t5", name: "Thamaskene Steel Two Hander" },
  sturgia_noble_sword_1_t5: { id: "sturgia_noble_sword_1_t5", name: "Thamaskene Steel Warsword" },
  ambassador_sword_t3: { id: "ambassador_sword_t3", name: "The Ambassador" },
  the_scalpel_sword_t3: { id: "the_scalpel_sword_t3", name: "The Scalpel" },
  eastern_spear_5_t5: { id: "eastern_spear_5_t5", name: "Thin Fine Steel Hewing Spear" },
  torch: { id: "torch", name: "Torch" },
  tournament_arrows: { id: "tournament_arrows", name: "Tournament Arrows" },
  tournament_bolts: { id: "tournament_bolts", name: "Tournament Bolts" },
  triangluar_spear_t3: { id: "triangluar_spear_t3", name: "Triangular Headed Spear" },
  eastern_throwing_spear_2_t4: { id: "eastern_throwing_spear_2_t4", name: "Triangular Throwing Spear" },
  tribal_steppe_shield: { id: "tribal_steppe_shield", name: "Tribal Steppe Shield" },
  tribal_bow: { id: "tribal_bow", name: "Tribesman Bow" },
  southern_throwing_axe_1_t4: { id: "southern_throwing_axe_1_t4", name: "Tribesman Throwing Axe" },
  desert_throwing_knife: { id: "desert_throwing_knife", name: "Tribesman Throwing Daggers" },
  cleaver_2hsword_t3: { id: "cleaver_2hsword_t3", name: "Two-Handed Cleaver" },
  tyrhung_sword_t3: { id: "tyrhung_sword_t3", name: "Tyrhung" },
  imperial_axe_t3: { id: "imperial_axe_t3", name: "Tzikourion" },
  sturgia_axe_4_t4: { id: "sturgia_axe_4_t4", name: "Veteran Warrior Axe" },
  vlandia_polearm_1_t5: { id: "vlandia_polearm_1_t5", name: "Voulge" },
  war_razor_2hsword_t4: { id: "war_razor_2hsword_t4", name: "War Razor" },
  sturgia_polearm_1_t5: { id: "sturgia_polearm_1_t5", name: "Warrazor" },
  eastern_spear_3_t3: { id: "eastern_spear_3_t3", name: "Weighted Steppe Spear" },
  footmans_wicker_shield: { id: "footmans_wicker_shield", name: "Wicker Shield" },
  eastern_wicker_shield: { id: "eastern_wicker_shield", name: "Wicker Square Shield" },
  eastern_wicker_sparring_shield: { id: "eastern_wicker_sparring_shield", name: "Wicker Square Tournament Shield" },
  vlandia_sword_5_t5: { id: "vlandia_sword_5_t5", name: "Wide Fullered Broad Arming Sword" },
  vlandia_2hsword_1_t5: { id: "vlandia_2hsword_1_t5", name: "Wide Fullered Broad Two Hander" },
  wide_heater_shield: { id: "wide_heater_shield", name: "Wide Heater Shield" },
  wide_leaf_spear_t4: { id: "wide_leaf_spear_t4", name: "Wide Leaf Spear" },
  winds_fury_sword_t3: { id: "winds_fury_sword_t3", name: "Winds Fury" },
  aserai_axe_1_t2: { id: "aserai_axe_1_t2", name: "Wood Splitter Axe" },
  bound_adarga: { id: "bound_adarga", name: "Wooden Adarga" },
  peasant_hammer_2_t1: { id: "peasant_hammer_2_t1", name: "Wooden Hammer" },
  old_horsemans_kite_shield: { id: "old_horsemans_kite_shield", name: "Wooden Kite Shield" },
  oval_shield: { id: "oval_shield", name: "Wooden Oval Shield" },
  wooden_sword_t1: { id: "wooden_sword_t1", name: "Wooden Sword" },
  wooden_sword_t2: { id: "wooden_sword_t2", name: "Wooden Sword" },
  wooden_2hsword_t1: { id: "wooden_2hsword_t1", name: "Wooden Twohander" },
  woodland_axe_t3: { id: "woodland_axe_t3", name: "Woodland axe" },
  northern_javelin_2_t3: { id: "northern_javelin_2_t3", name: "Woodland Javelin" },
  woodland_longbow: { id: "woodland_longbow", name: "Woodland Longbow" },
  woodland_yew_bow: { id: "woodland_yew_bow", name: "Woodland Yew Bow" },
  worn_kite_shield: { id: "worn_kite_shield", name: "Worn Kite Shield" },
  gladius_b: { id: "gladius_b", name: "Xiphos" },
  lowland_yew_bow: { id: "lowland_yew_bow", name: "Yew Bow" },
};
