export const demoWanderers: any[] = [
  {
    id: 'demowanderers_farquaad',
    name: 'Farquaad',
    voice: 'softspoken',
    culture: 'empire',
    battleTemplate: 'empire_lord_lady_battle_equipment',
    civilianTemplate: 'empire_unarmored_noble_equipment',
    isFemale: false,
    face: {
      bodyProperties: {
        version: '4',
        age: '30.9',
        weight: '0.4',
        build: '0',
        key:
          '0005080E40FC000BAE7EFF0EEFC0FF1F01FF87808E00F00500180E0F8FF0F0F00100661400F8FFFF00000000000000000000000000000000000000007E043002',
      },
    },
    skills: {
      OneHanded: 120,
      TwoHanded: 100,
      Polearm: 100,
      Bow: 60,
      Crossbow: 60,
      Throwing: 60,
      Riding: 100,
      Athletics: 100,
      Scouting: 100,
      Tactics: 60,
      Roguery: 250,
      Charm: 100,
      Leadership: 60,
      Trade: 60,
      Steward: 10,
      Medicine: 10,
      Engineering: 10,
    },
    traits: { Calculating: '-2', Generosity: '-2', Honor: '-2', Mercy: '-2', Valor: '-1' },
    dialogue: {
      prebackstory:
        'Forgive me, princess, for startling you but you startled me. For I have never seen such a radiant beauty before. I... am Lord Farquaad.',
      backstory_a: 'Some of you may die, but that is a sacrifice I am willing to make.',
      backstory_b: "Run, run, run as fast as you can. You can't catch me, I'm the Gingerbread Man!",
      response_1: 'You seem like a fine king.',
      response_2: 'Get ogre with it.',
      backstory_c: 'Mirror, mirror, on the wall. Is this not the most perfect kingdom of them all?',
      backstory_d: 'Knights, new plan! The one who kills the ogre, will be named champion!',
    },
  },
  {
    id: 'demowanderers_swanson',
    name: 'Swanson',
    voice: 'curt',
    culture: 'battania',
    battleTemplate: 'npc_companion_equipment_template_battania',
    civilianTemplate: 'npc_armed_wanderer_equipment_template_battania',
    isFemale: false,
    face: {
      bodyProperties: {
        version: '4',
        age: '25',
        weight: '0.5',
        build: '0.6',
        key:
          '0005040A002C280E808258024196312BF44A300546B807308A09100E89C41056018976130807A8F60000000000000000000000000000000000000000151C3102',
      },
    },
    skills: {
      OneHanded: 200,
      TwoHanded: 200,
      Polearm: 200,
      Bow: 200,
      Crossbow: 200,
      Throwing: 200,
      Riding: 100,
      Athletics: 100,
      Crafting: 100,
      Scouting: 100,
      Tactics: 100,
      Charm: 100,
      Leadership: 100,
      Trade: 50,
      Steward: 50,
      Medicine: 50,
      Engineering: 50,
    },
    traits: { Calculating: '-1', Generosity: '0', Honor: '1', Mercy: '0', Valor: '2' },
    dialogue: {
      backstory_d: 'Don’t start chasing applause and acclaim. That way lies madness.',
      backstory_b:
        'The less I know about other people’s affairs, the happier I am. I’m not interested in caring about people. I once worked with a guy for three years and never learned his name. Best friend I ever had. We still never talk sometimes.',
      backstory_a:
        'When people get too chummy with me, I like to call them by the wrong name to let them know I don’t really care about them.',
      prebackstory: 'If there were more food and fewer people, this would be a perfect party.',
      backstory_c:
        'Under my tutelage, you will grow from boys to men. From men into gladiators. And from gladiators into Swansons.',
      response_1: 'Teach me, master!',
      response_2: 'What?',
    },
  },
  {
    id: 'demowanderers_of_the blackwater',
    name: 'of the Blackwater',
    voice: 'ironic',
    culture: 'vlandia',
    battleTemplate: 'npc_armed_wanderer_equipment_template_vlandia',
    civilianTemplate: 'npc_wanderer_equipment_template_vlandia',
    isFemale: false,
    face: {
      bodyProperties: {
        version: '4',
        age: '25.84',
        weight: '0.5',
        build: '0.5',
        key:
          '0016000B54FC13437A824269551279772138526563789435969939079E843002019776130956596400000000000000000000000000000000000000004F3C3002',
      },
    },
    skills: {
      OneHanded: 200,
      TwoHanded: 200,
      Polearm: 100,
      Bow: 150,
      Crossbow: 200,
      Throwing: 150,
      Riding: 200,
      Athletics: 150,
      Crafting: 50,
      Scouting: 100,
      Tactics: 100,
      Roguery: 150,
      Charm: 80,
      Leadership: 100,
      Trade: 100,
      Steward: 40,
      Medicine: 100,
      Engineering: 60,
    },
    traits: { Calculating: '1', Generosity: '-2', Honor: '-1', Mercy: '0', Valor: '1' },
    dialogue: {
      prebackstory:
        "The smart place to meet is in a tavern. That way if one party is late, the other can drink some ale. Need help to take a castle? I'm your man.",
      backstory_c: 'I like you well enough, ugly little whoreson that you are ...',
      backstory_b:
        'That’s how all the great houses started, isn’t it? With a hard bastard who was good at killing people. Kill a few hundred people, they make you a lord. Kill a few thousand, they make you king.',
      response_1: 'Thanks?',
      response_2: "You don't seem very nice.",
      backstory_d: "You waste time to get people to love you, you'll end up the most popular dead man in town.",
      backstory_a: "Give me 10 good men and some climbing pikes, and I'll impregnate the bitch.",
    },
  },
];
