import { Culture } from './types/culture';
import { EquipmentTemplate } from './types/equipment';
import { FaceTemplate } from './types/faceTemplates';
import { Beard, HairMale, HairFemale } from './types/face';
import { Skill } from './types/skills';
import { Trait, TraitVariant } from './types/traits';
import { Voice } from './types/voices';

export const CultureLabels = {
  [Culture.Aserai]: 'Aserai',
  [Culture.Battania]: 'Battanian',
  [Culture.Empire]: 'Imperial',
  [Culture.Khuzait]: 'Khuzait',
  [Culture.Sturgia]: 'Sturgian',
  [Culture.Vlandia]: 'Vlandian',
};

export const VoiceLabels = {
  [Voice.Curt]: 'Curt',
  [Voice.Earnest]: 'Earnest',
  [Voice.Ironic]: 'Ironic',
  [Voice.SoftSpoken]: 'Soft-spoken',
};

export const SkillLabels = {
  [Skill.OneHanded]: 'One-Handed',
  [Skill.TwoHanded]: 'Two-Handed',
  [Skill.Polearm]: 'Polearm',
  [Skill.Bow]: 'Bow',
  [Skill.Crossbow]: 'Crossbow',
  [Skill.Throwing]: 'Throwing',
  [Skill.Riding]: 'Riding',
  [Skill.Athletics]: 'Athletics',
  [Skill.Crafting]: 'Smithing',
  [Skill.Scouting]: 'Scouting',
  [Skill.Tactics]: 'Tactics',
  [Skill.Rougery]: 'Roguery',
  [Skill.Charm]: 'Charm',
  [Skill.Leadership]: 'Leadership',
  [Skill.Trade]: 'Trade',
  [Skill.Steward]: 'Steward',
  [Skill.Medicine]: 'Medicine',
  [Skill.Engineering]: 'Engineering',
};

export const TraitLabels = {
  [Trait.Calculating]: 'Calculating',
  [Trait.Generosity]: 'Generosity',
  [Trait.Honor]: 'Honor',
  [Trait.Mercy]: 'Mercy',
  [Trait.Valor]: 'Valor',
};

export const TraitVariantLabels = {
  [Trait.Calculating]: {
    [TraitVariant.Minus2]: 'Hotheaded',
    [TraitVariant.Minus1]: 'Impulsive',
    [TraitVariant.Plus1]: 'Calculating',
    [TraitVariant.Plus2]: 'Cerebral',
  },
  [Trait.Mercy]: {
    [TraitVariant.Minus2]: 'Sadistic',
    [TraitVariant.Minus1]: 'Cruel',
    [TraitVariant.Plus1]: 'Merciful',
    [TraitVariant.Plus2]: 'Compassionate',
  },
  [Trait.Valor]: {
    [TraitVariant.Minus2]: 'Very cautious',
    [TraitVariant.Minus1]: 'Cautious',
    [TraitVariant.Plus1]: 'Daring',
    [TraitVariant.Plus2]: 'Fearless',
  },
  [Trait.Honor]: {
    [TraitVariant.Minus2]: 'Deceitful',
    [TraitVariant.Minus1]: 'Devious',
    [TraitVariant.Plus1]: 'Honest',
    [TraitVariant.Plus2]: 'Honorable',
  },
  [Trait.Generosity]: {
    [TraitVariant.Minus2]: 'Tightfisted',
    [TraitVariant.Minus1]: 'Closefisted',
    [TraitVariant.Plus1]: 'Generous',
    [TraitVariant.Plus2]: 'Munificent',
  },
};

export const HairLabels = {
  [HairMale.Bald]: 'Bald',
  [HairMale.Short]: 'Short',
  [HairMale.ShortAndThin]: 'Short and thin',
  [HairMale.Tousled]: 'Tousled',
  [HairMale.SlickedLong]: 'Slicked, long',
  [HairMale.PageBoy]: 'Page boy',
  [HairMale.LongAndBushy]: 'Long and bushy',
  [HairMale.Bowl]: 'Bowl',
  [HairFemale.Bobbed]: 'Bobbed',
  [HairFemale.RestingOnShoulders]: 'Resting on shoulders',
  [HairFemale.ShoulderLengthTied]: 'Shoulder length, tied',
  [HairFemale.AboveShoudlerLength]: 'Above shoulder lengh',
  [HairFemale.TiedLongOverShoulder]: 'Tied over shoulder, long',
  [HairFemale.LongOverShoulder]: 'Over shoulder, long',
  [HairFemale.BraidedAboveEars]: 'Braided above ears',
  [HairFemale.TiedInBack]: 'Tied in back',
  [HairFemale.Ukrainian]: 'Ukrainian',
};

export const BeardLabels = {
  [Beard.LightShort]: 'Short beard, light',
  [Beard.HeavyShort]: 'Short beard, heavy',
  [Beard.CleanShaven]: 'Clean-shaven',
  [Beard.DroopyMustache]: 'Droopy mustache',
  [Beard.MediumMustache]: 'Medium mustache',
  [Beard.BeardWithShavedCheeks]: 'Beard with shaved cheeks',
  [Beard.BushyGoatee]: 'Bushy goatee',
  [Beard.HeavyLongBeard]: 'Long beard, heavy',
  [Beard.LongScragglyBeard]: 'Long beard, scraggly',
};

export const FaceTemplateLabels = {
  [FaceTemplate.VillagerAserai]: 'Aserai Villager',
  [FaceTemplate.VillagerBattania]: 'Battanian Villager',
  [FaceTemplate.VillagerEmpire]: 'Imperial Villager',
  [FaceTemplate.VillagerKhuzait]: 'Khuzait Villager',
  [FaceTemplate.VillagerVlandia]: 'Vlandian Villager',

  [FaceTemplate.TownsmanAserai]: 'Aserai Townsman',
  [FaceTemplate.TownsmanBattania]: 'Battanian Townsman',
  [FaceTemplate.TownsmanEmpire]: 'Imperial Townsman',
  [FaceTemplate.TownsmanKhuzait]: 'Khuzait Townsman',
  [FaceTemplate.TownsmanVlandia]: 'Vlandian Townsman',

  [FaceTemplate.VillageWomanAserai]: 'Aserai Villager',
  [FaceTemplate.VillageWomanBattania]: 'Battanian Villager',
  [FaceTemplate.VillageWomanEmpire]: 'Imperial Villager',
  [FaceTemplate.VillageWomanKhuzait]: 'Khuzait Villager',
  [FaceTemplate.VillageWomanVlandia]: 'Vlandian Villager',

  [FaceTemplate.BeggarAserai]: 'Aserai Beggar',
  [FaceTemplate.BeggarBattania]: 'Battanian Beggar',
  [FaceTemplate.BeggarEmpire]: 'Imperial Beggar',
  [FaceTemplate.BeggarKhuzait]: 'Khuzait Beggar',
  [FaceTemplate.BeggarSturgia]: 'Sturgian Beggar',
  [FaceTemplate.BeggarVlandia]: 'Vlandian Beggar',

  [FaceTemplate.TownswomanAserai]: 'Aserai Townswoman',
  [FaceTemplate.TownswomanBattania]: 'Battanian Townswoman',
  [FaceTemplate.TownswomanEmpire]: 'Imperial Townswoman',
  [FaceTemplate.TownswomanKhuzait]: 'Khuzait Townswoman',
  [FaceTemplate.TownswomanVlandia]: 'Vlandian Townswoman',

  [FaceTemplate.BanditDesert]: 'Desert Bandit',
  [FaceTemplate.BanditForest]: 'Forest Bandit',
  [FaceTemplate.BanditMountain]: 'Mountain Bandit',
  [FaceTemplate.BanditSteppe]: 'Steppe Bandit',
  [FaceTemplate.BanditSeaRaider]: 'Sea Raider',
};

export const EquipmentLabels = {
  [EquipmentTemplate.AseraiRecruit]: 'Aserai Recruit',
  [EquipmentTemplate.AseraiTribesman]: 'Aserai Tribesman',
  [EquipmentTemplate.AseraiFootman]: 'Aserai Footman',
  [EquipmentTemplate.AseraiSkirmisher]: 'Aserai Skirmisher',
  [EquipmentTemplate.AseraiArcher]: 'Aserai Archer',
  [EquipmentTemplate.AseraiMasterArcher]: 'Aserai Master Archer',
  [EquipmentTemplate.AseraiInfantry]: 'Aserai Infantry',
  [EquipmentTemplate.AseraiVeteranInfantry]: 'Aserai Veteran Infantry',
  [EquipmentTemplate.AseraiMamelukeSoldier]: 'Aserai Mameluke Soldier',
  [EquipmentTemplate.AseraiMamelukeRegular]: 'Aserai Mameluke Regular',
  [EquipmentTemplate.AseraiMamelukeCavalry]: 'Aserai Mameluke Cavalry',
  [EquipmentTemplate.AseraiMamelukeHeavyCavalry]: 'Aserai Mameluke Heavy Cavalry',
  [EquipmentTemplate.AseraiMamelukeAxeman]: 'Aserai Mameluke Axeman',
  [EquipmentTemplate.AseraiMamelukeGuard]: 'Aserai Mameluke Guard',
  [EquipmentTemplate.MamlukePalaceGuard]: 'Aserai Mameluke Palace Guard',
  [EquipmentTemplate.AseraiYouth]: 'Aserai Youth',
  [EquipmentTemplate.AseraiTribalHorseman]: 'Aserai Tribal Horseman',
  [EquipmentTemplate.AseraiFaris]: 'Aserai Faris',
  [EquipmentTemplate.AseraiVeteranFaris]: 'Aserai Veteran Faris',
  [EquipmentTemplate.BattanianVolunteer]: 'Battanian Volunteer',
  [EquipmentTemplate.BattanianClanwarrior]: 'Battanian Clan Warrior',
  [EquipmentTemplate.BattanianTrainedWarrior]: 'Battanian Trained Warrior',
  [EquipmentTemplate.BattanianPickedWarrior]: 'Battanian Picked Warrior',
  [EquipmentTemplate.BattanianOathsworn]: 'Battanian Trained Spearman',
  [EquipmentTemplate.BattanianScout]: 'Battanian Scout',
  [EquipmentTemplate.BattanianMountedSkirmisher]: 'Battanian Mounted Skirmisher',
  [EquipmentTemplate.BattanianHorseman]: 'Battanian Horseman',
  [EquipmentTemplate.BattanianWoodrunner]: 'Battanian Wood Runner',
  [EquipmentTemplate.BattanianRaider]: 'Battanian Raider',
  [EquipmentTemplate.BattanianSkirmisher]: 'Battanian Skirmisher',
  [EquipmentTemplate.BattanianWildling]: 'Battanian Wildling',
  [EquipmentTemplate.BattanianFalxman]: 'Battanian Falxman',
  [EquipmentTemplate.BattanianVeteranSkirmisher]: 'Battanian Veteran Skirmisher',
  [EquipmentTemplate.BattanianVeteranFalxman]: 'Battanian Veteran Falxman',
  [EquipmentTemplate.BattanianHighbornYouth]: 'Battanian Highborn Youth',
  [EquipmentTemplate.BattanianHighbornWarrior]: 'Battanian Highborn Warrior',
  [EquipmentTemplate.BattanianHero]: 'Battanian Hero',
  [EquipmentTemplate.BattanianFian]: 'Battanian Fian',
  [EquipmentTemplate.BattanianFianChampion]: 'Battanian Fian Champion',
  [EquipmentTemplate.Archer]: 'Archer',
  [EquipmentTemplate.ImperialRecruit]: 'Imperial Recruit',
  [EquipmentTemplate.ImperialInfantryman]: 'Imperial Infantryman',
  [EquipmentTemplate.ImperialViglaRecruit]: 'Imperial Vigla Recruit',
  [EquipmentTemplate.ImperialEquite]: 'Imperial Equite',
  [EquipmentTemplate.ImperialHeavyHorseman]: 'Imperial Heavy Horseman',
  [EquipmentTemplate.ImperialCataphract]: 'Imperial Cataphract',
  [EquipmentTemplate.ImperialEliteCataphract]: 'Imperial Elite Cataphract',
  [EquipmentTemplate.ImperialTrainedInfantryman]: 'Imperial Trained Infantryman',
  [EquipmentTemplate.ImperialVeteranInfantryman]: 'Imperial Veteran Infantryman',
  [EquipmentTemplate.ImperialLegionary]: 'Imperial Legionary',
  [EquipmentTemplate.ImperialArcher]: 'Imperial Archer',
  [EquipmentTemplate.Bucellarii]: 'Imperial Bucellarii',
  [EquipmentTemplate.ImperialTrainedArcher]: 'Imperial Trained Archer',
  [EquipmentTemplate.ImperialVeteranArcher]: 'Imperial Veteran Archer',
  [EquipmentTemplate.ImperialPalatineGuard]: 'Imperial Palatine Guard',
  [EquipmentTemplate.ImperialMenavliaton]: 'Imperial Menavliaton',
  [EquipmentTemplate.ImperialEliteMenavliaton]: 'Imperial Elite Menavliaton',
  [EquipmentTemplate.ImperialCrossbowman]: 'Imperial Crossbowman',
  [EquipmentTemplate.ImperialSergeantCrossbowman]: 'Imperial Sergeant Crossbowman',
  [EquipmentTemplate.KhuzaitNomad]: 'Khuzait Nomad',
  [EquipmentTemplate.KhuzaitFootman]: 'Khuzait Footman',
  [EquipmentTemplate.KhuzaitTribalWarrior]: 'Khuzait Tribal Warrior',
  [EquipmentTemplate.KhuzaitNobleSon]: "Khuzait Noble's Son",
  [EquipmentTemplate.KhuzaitHunter]: 'Khuzait Hunter',
  [EquipmentTemplate.KhuzaitSpearman]: 'Khuzait Spearman',
  [EquipmentTemplate.KhuzaitRaider]: 'Khuzait Raider',
  [EquipmentTemplate.KhuzaitHorseman]: 'Khuzait Horseman',
  [EquipmentTemplate.KhuzaitQanqli]: 'Khuzait Qanqli',
  [EquipmentTemplate.KhuzaitArcher]: 'Khuzait Archer',
  [EquipmentTemplate.KhuzaitSpearInfantry]: 'Khuzait Spear Infantry',
  [EquipmentTemplate.KhuzaitHorseArcher]: 'Khuzait Horse Archer',
  [EquipmentTemplate.KhuzaitLancer]: 'Khuzait Lancer',
  [EquipmentTemplate.KhuzaitTorguud]: 'Khuzait Torguud',
  [EquipmentTemplate.KhuzaitMarksman]: 'Khuzait Marksman',
  [EquipmentTemplate.KhuzaitDarkhan]: 'Khuzait Darkhan',
  [EquipmentTemplate.KhuzaitHeavyHorseArcher]: 'Khuzait Heavy Horse Archer',
  [EquipmentTemplate.KhuzaitHeavyLancer]: 'Khuzait Heavy Lancer',
  [EquipmentTemplate.KhuzaitKheshig]: 'Khuzait Kheshig',
  [EquipmentTemplate.KhuzaitKhansGuard]: "Khuzait Khan's Guard",
  [EquipmentTemplate.SturgianRecruit]: 'Sturgian Recruit',
  [EquipmentTemplate.SturgianWarrior]: 'Sturgian Warrior',
  [EquipmentTemplate.SturgianSoldier]: 'Sturgian Soldier',
  [EquipmentTemplate.SturgianShockTroop]: 'Sturgian Shock Troop',
  [EquipmentTemplate.SturgianVeteranWarrior]: 'Sturgian Veteran Warrior',
  [EquipmentTemplate.SturgianWarriorSon]: 'Sturgian Warrior Son',
  [EquipmentTemplate.Varyag]: 'Varyag',
  [EquipmentTemplate.VaryagVeteran]: 'Varyag Veteran',
  [EquipmentTemplate.Druzhinnik]: 'Sturgian Druzhinnik',
  [EquipmentTemplate.DruzhinnikChampion]: 'Sturgian Druzhinnik Champion',
  [EquipmentTemplate.SturgianWoodsman]: 'Sturgian Woodsman',
  [EquipmentTemplate.SturgianHunter]: 'Sturgian Hunter',
  [EquipmentTemplate.SturgianArcher]: 'Sturgian Archer',
  [EquipmentTemplate.SturgianVeteranBowman]: 'Sturgian Veteran Bowman',
  [EquipmentTemplate.SturgianBrigand]: 'Sturgian Brigand',
  [EquipmentTemplate.SturgianHardenedBrigand]: 'Sturgian Hardened Brigand',
  [EquipmentTemplate.SturgianHorseRaider]: 'Sturgian Horse Raider',
  [EquipmentTemplate.SturgianBerzerker]: 'Sturgian Berserker',
  [EquipmentTemplate.SturgianSpearman]: 'Sturgian Spearman',
  [EquipmentTemplate.SturgianUlfhednar]: 'Sturgian Ulfhednar',
  [EquipmentTemplate.VlandianRecruit]: 'Vlandian Recruit',
  [EquipmentTemplate.VlandianFootman]: 'Vlandian Footman',
  [EquipmentTemplate.VlandianSpearman]: 'Vlandian Spearman',
  [EquipmentTemplate.VlandianBillman]: 'Vlandian Billman',
  [EquipmentTemplate.VlandianVoulgier]: 'Vlandian Voulgier',
  [EquipmentTemplate.VlandianPikeman]: 'Vlandian Pikeman',
  [EquipmentTemplate.VlandianInfantry]: 'Vlandian Infantry',
  [EquipmentTemplate.VlandianSwordsman]: 'Vlandian Swordsman',
  [EquipmentTemplate.VlandianSergeant]: 'Vlandian Sergeant',
  [EquipmentTemplate.VlandianLightCavalry]: 'Vlandian Light Cavalry',
  [EquipmentTemplate.VlandianVanguard]: 'Vlandian Vanguard',
  [EquipmentTemplate.VlandianLevyCrossbowman]: 'Vlandian Levy Crossbowman',
  [EquipmentTemplate.VlandianCrossbowman]: 'Vlandian Crossbowman',
  [EquipmentTemplate.VlandianHardenedCrossbowman]: 'Vlandian Hardened Crossbowman',
  [EquipmentTemplate.VlandianSharpshooter]: 'Vlandian Sharpshooter',
  [EquipmentTemplate.VlandianSquire]: 'Vlandian Squire',
  [EquipmentTemplate.VlandianGallant]: 'Vlandian Gallant',
  [EquipmentTemplate.VlandianKnight]: 'Vlandian Knight',
  [EquipmentTemplate.VlandianChampion]: 'Vlandian Champion',
  [EquipmentTemplate.VlandianBannerKnight]: 'Vlandian Banner Knight',
  [EquipmentTemplate.GhilmanTier1]: 'Koleman',
  [EquipmentTemplate.GhilmanTier2]: 'Ghilman',
  [EquipmentTemplate.GhilmanTier3]: 'Ghulam',
  [EquipmentTemplate.GalloglassTier1]: 'Skene',
  [EquipmentTemplate.GalloglassTier2]: 'Kern',
  [EquipmentTemplate.GalloglassTier3]: 'Redshank',
  [EquipmentTemplate.LegionOfTheBetrayedTier1]: 'Hastati',
  [EquipmentTemplate.LegionOfTheBetrayedTier2]: 'Principes',
  [EquipmentTemplate.LegionOfTheBetrayedTier3]: 'Triarii',
  [EquipmentTemplate.SkolderbrotvaTier1]: 'Skolder Recruit',
  [EquipmentTemplate.SkolderbrotvaTier2]: 'Skolder Warrior Brotva',
  [EquipmentTemplate.SkolderbrotvaTier3]: 'Skolder Veteran Brotva',
  [EquipmentTemplate.CompanyOfTheBoarTier1]: 'Boar Novice',
  [EquipmentTemplate.CompanyOfTheBoarTier2]: 'Boar Veteran',
  [EquipmentTemplate.CompanyOfTheBoarTier3]: 'Boar Champion',
  [EquipmentTemplate.BeniZilalTier1]: 'Beni Zilal Recruit',
  [EquipmentTemplate.BeniZilalTier2]: 'Beni Zilal Soldier',
  [EquipmentTemplate.BeniZilalTier3]: 'Beni Zilal Royal Guard',
  [EquipmentTemplate.WolfskinsTier1]: 'Young Wolf',
  [EquipmentTemplate.WolfskinsTier2]: 'Seasoned Wolf',
  [EquipmentTemplate.WolfskinsTier3]: 'Chosen Wolf',
  [EquipmentTemplate.HiddenHandTier1]: 'Hidden Pawn',
  [EquipmentTemplate.HiddenHandTier2]: 'Hidden Hand',
  [EquipmentTemplate.HiddenHandTier3]: 'Puppeteer',
  [EquipmentTemplate.LakepikeTier1]: 'Skolder Recruit',
  [EquipmentTemplate.LakepikeTier2]: 'Skolder Warrior Brotva',
  [EquipmentTemplate.LakepikeTier3]: 'Skolder Veteran Brotva',
  [EquipmentTemplate.GuardiansTier1]: 'Guardian Recruit',
  [EquipmentTemplate.GuardiansTier2]: 'Expert Guardian',
  [EquipmentTemplate.GuardiansTier3]: 'Veteran Guardian',
  [EquipmentTemplate.EmbersOfFlameTier1]: 'Oath Keeper Recruit',
  [EquipmentTemplate.EmbersOfFlameTier2]: 'Expert Oath Keeper',
  [EquipmentTemplate.EmbersOfFlameTier3]: 'Veteran Oath Keeper',
  [EquipmentTemplate.JawwalTier1]: 'Jawwal Recruit',
  [EquipmentTemplate.JawwalTier2]: 'Jawwal Camel Rider',
  [EquipmentTemplate.JawwalTier3]: 'Jawwal Bedouin',
  [EquipmentTemplate.KarakhuzaitsTier1]: 'Karakhuzait Nomad',
  [EquipmentTemplate.KarakhuzaitsTier2]: 'Karakhuzait Rider',
  [EquipmentTemplate.KarakhuzaitsTier3]: 'Karakhuzait Elder',
  [EquipmentTemplate.ForestPeopleTier1]: 'Recruit Forester',
  [EquipmentTemplate.ForestPeopleTier2]: 'Expert Forester',
  [EquipmentTemplate.ForestPeopleTier3]: 'Veteran Forester',
  [EquipmentTemplate.EleftheroiTier1]: 'Recruit Eleftheroi',
  [EquipmentTemplate.EleftheroiTier2]: 'Expert Eleftheroi',
  [EquipmentTemplate.EleftheroiTier3]: 'Veteran Eleftheroi',
  [EquipmentTemplate.Mercenary1]: 'Watchman',
  [EquipmentTemplate.Mercenary2]: 'Mercenary Guard',
  [EquipmentTemplate.Mercenary3]: 'Mercenary Scout',
  [EquipmentTemplate.Mercenary4]: 'Mercenary Swordsman',
  [EquipmentTemplate.Mercenary5]: 'Mercenary Crossbowman',
  [EquipmentTemplate.Mercenary6]: 'Mercenary Horseman',
  [EquipmentTemplate.Mercenary7]: 'Hired Blade',
  [EquipmentTemplate.Mercenary8]: 'Hired Crossbow',
  [EquipmentTemplate.Mercenary9]: 'Mercenary Cavalry',
  [EquipmentTemplate.Gangster1]: 'Thug',
  [EquipmentTemplate.Gangster2]: 'Expert Thug',
  [EquipmentTemplate.Gangster3]: 'Master Thug',
  [EquipmentTemplate.SwordSister]: 'Sword Sister',
  [EquipmentTemplate.ArmedTraderAserai]: 'Aserai Armed Trader',
  [EquipmentTemplate.ArmedTraderBattania]: 'Battanian Armed Trader',
  [EquipmentTemplate.ArmedTraderEmpire]: 'Imperial Armed Trader',
  [EquipmentTemplate.ArmedTraderKhuzait]: 'Khuzait Armed Trader',
  [EquipmentTemplate.ArmedTraderSturgia]: 'Sturgian Armed Trader',
  [EquipmentTemplate.ArmedTraderVlandia]: 'Vlandian Armed Trader',
  [EquipmentTemplate.HuskarlSwordsman]: 'Huskarl Swordsman',
  [EquipmentTemplate.Looter]: 'Looter',
  [EquipmentTemplate.Deserter]: 'Deserter',
  [EquipmentTemplate.SeaRaidersBandit]: 'Sea Raider',
  [EquipmentTemplate.SeaRaidersRaider]: 'Sea Raider Warrior',
  [EquipmentTemplate.SeaRaidersChief]: 'Sea Raider Chief',
  [EquipmentTemplate.MountainBanditsBandit]: 'Hillmen',
  [EquipmentTemplate.MountainBanditsRaider]: 'Brigand',
  [EquipmentTemplate.MountainBanditsChief]: 'Highwayman',
  [EquipmentTemplate.ForestBanditsBandit]: 'Bushwacker',
  [EquipmentTemplate.ForestBanditsRaider]: 'Freebooter',
  [EquipmentTemplate.ForestBanditsChief]: 'Forest Bandit',
  [EquipmentTemplate.DesertBanditsBandit]: 'Bedouin Rover',
  [EquipmentTemplate.DesertBanditsRaider]: 'Nomad Bandit',
  [EquipmentTemplate.DesertBanditsChief]: 'Harami',
  [EquipmentTemplate.SteppeBanditsBandit]: 'Steppe Bandit',
  [EquipmentTemplate.SteppeBanditsRaider]: 'Marauder',
  [EquipmentTemplate.SteppeBanditsChief]: 'Raider',
  [EquipmentTemplate.SeaRaidersBoss]: 'Sea Raider Boss',
  [EquipmentTemplate.MountainBanditsBoss]: 'Mountain Bandit Boss',
  [EquipmentTemplate.ForestBanditsBoss]: 'Forest Bandit Boss',
  [EquipmentTemplate.DesertBanditsBoss]: 'Desert Bandit Boss',
  [EquipmentTemplate.SteppeBanditsBoss]: 'Steppe Bandit Boss',
  [EquipmentTemplate.TemplateNpcWandererEquipmentBattania]: 'Wanderer Equipment Battanian',
  [EquipmentTemplate.TemplateNpcArmedWandererEquipmentBattania]: 'Armed Wanderer Equipment Battanian',
  [EquipmentTemplate.TemplateNpcWandererEquipmentEmpire]: 'Wanderer Equipment Imperial',
  [EquipmentTemplate.TemplateNpcArmedWandererEquipmentEmpire]: 'Armed Wanderer Equipment Imperial',
  [EquipmentTemplate.TemplateNpcWandererEquipmentAserai]: 'Wanderer Equipment Aserai',
  [EquipmentTemplate.TemplateNpcArmedWandererEquipmentAserai]: 'Armed Wanderer Equipment Aserai',
  [EquipmentTemplate.TemplateNpcArmedWandererEquipmentKhuzait]: 'Armed Wanderer Equipment Khuzait',
  [EquipmentTemplate.TemplateNpcCompanionEquipmentKhuzait]: 'Companion Equipment Khuzait',
  [EquipmentTemplate.TemplateNpcWandererEquipmentVlandia]: 'Wanderer Equipment Vlandian',
  [EquipmentTemplate.TemplateNpcArmedWandererEquipmentVlandia]: 'Armed Wanderer Equipment Vlandian',
  [EquipmentTemplate.TemplateNpcCompanionEquipmentVlandia]: 'Companion Equipment Vlandian',
  [EquipmentTemplate.TemplateNpcCompanionEquipmentBattania]: 'Companion Equipment Battanian',
  [EquipmentTemplate.TemplateNpcWandererEquipmentSturgia]: 'Wanderer Equipment Sturgian',
  [EquipmentTemplate.TemplateNpcArmedWandererEquipmentSturgia]: 'Armed Wanderer Equipment Sturgian',
  [EquipmentTemplate.TemplateNpcWandererEquipmentKhuzait]: 'Wanderer Equipment Khuzait',
  [EquipmentTemplate.EmpireNobleBattleEquipment]: 'Imperial Noble Battle Equipment',
  [EquipmentTemplate.KhuzaitNobleBattleEquipment]: 'Khuzait Noble Battle Equipment',
  [EquipmentTemplate.BattaniaNobleBattleEquipment]: 'Battanian Noble Battle Equipment',
  [EquipmentTemplate.SturgiaNobleBattleEquipment]: 'Sturgian Noble Battle Equipment',
  [EquipmentTemplate.VlandiaNobleBattleEquipment]: 'Vlandian Noble Battle Equipment',
  [EquipmentTemplate.AseraiNobleBattleEquipment]: 'Aserai Noble Battle Equipment',
  [EquipmentTemplate.AseraiNobleBattleEquipmentHeavy]: 'Aserai Noble Battle Equipment Heavy',
  [EquipmentTemplate.BattaniaNobleBattleEquipmentHeavy]: 'Battanian Noble Battle Equipment Heavy',
  [EquipmentTemplate.EmpireNobleBattleEquipmentHeavy]: 'Imperial Noble Battle Equipment Heavy',
  [EquipmentTemplate.KhuzaitNobleBattleEquipmentHeavy]: 'Khuzait Noble Battle Equipment Heavy',
  [EquipmentTemplate.SturgiaNobleBattleEquipmentHeavy]: 'Sturgian Noble Battle Equipment Heavy',
  [EquipmentTemplate.VlandiaNobleBattleEquipmentHeavy]: 'Vlandian Noble Battle Equipment Heavy',
  [EquipmentTemplate.AseraiUnarmoredNobleEquipment]: 'Aserai Unarmored Noble Equipment',
  [EquipmentTemplate.BattaniaUnarmoredNobleEquipment]: 'Battanian Unarmored Noble Equipment',
  [EquipmentTemplate.EmpireUnarmoredNobleEquipment]: 'Imperial Unarmored Noble Equipment',
  [EquipmentTemplate.KhuzaitUnarmoredNobleEquipment]: 'Khuzait Unarmored Noble Equipment',
  [EquipmentTemplate.SturgiaUnarmoredNobleEquipment]: 'Sturgian Unarmored Noble Equipment',
  [EquipmentTemplate.VlandiaUnarmoredNobleEquipment]: 'Vlandian Unarmored Noble Equipment',
  [EquipmentTemplate.VillagerKhuzait]: 'Villager Khuzait',
  [EquipmentTemplate.VillagerEmpire]: 'Villager Imperial',
  [EquipmentTemplate.VillagerAserai]: 'Villager Aserai',
  [EquipmentTemplate.VillagerSturgia]: 'Villager Sturgian',
  [EquipmentTemplate.VillagerVlandia]: 'Villager Vlandian',
  [EquipmentTemplate.VillagerBattania]: 'Villager Battanian',
  [EquipmentTemplate.TemplateNpcCompanionEquipmentSturgia]: 'Companion Equipment Sturgian',
  [EquipmentTemplate.TemplateNpcCompanionEquipmentAserai]: 'Companion Equipment Aserai',
  [EquipmentTemplate.TemplateNpcCompanionEquipmentEmpire]: 'Companion Equipment Imperial',
};
